### ISSUE TITLE
Library/cache behavior

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/public-digital-library#120]
I go there: http://library-dev.bdrc.io/show/bdr:W22073
Then when I click on the images to open the viewer, I get nothing to view in the viewer and the following failing link in the console:

http://iiifpres-dev.bdrc.io/collection/wio:bdr:MW22073?continuous=true

If I open this link in a different tab (i.e going directly to iiifpres) then it works

If i go to http://library-dev.bdrc.io/show/bdr:W22073 using Chrome private navigation, everything works.

So now, I am obviously facing a cache issue:

1) How can I go back to normal and see things as they are (in other words, how can I empty the cache related to the library and only this cache)
2) It seems like the library and the browser are not using the same cache since I have the same url failing in the library tab and working in another tab when accessed directly. How can this happen?

**Comment by eroux** [comment]
Well, there are cache problems in some places, but I think this is probably a cache problem in iiifpres more than the library... there might be places where the response has a non-200 code with some cache instructions, which would not be good

**Comment by MarcAgate** [comment]
How come I get 404 in one tab and 200 in a different tab from the same browser at the same time ? How could that be server related ?

**Comment by berger-n** [comment]
this might be related to an issue I have on https://bdrc-reader.github.io/mugey-gonpa/tsannyid
it's been months but when I go on that page just now, in the iframe I see "Page not found: /scripts/embed-iframe.html / Redirecting...", even if I fully reload page with cache disabled etc.
but if I open it in private navigation it shows the collection tree and everything is fine

**Comment by MarcAgate** [comment]
One more info: the issue is even more bizarre than I thought since it's not only that I cannot view images and/or volumes for that given work, it is for ANY work! 
this time (for instance) , this is the failing url:
http://iiifpres-dev.bdrc.io/collection/wio:bdr:MW27883?continuous=true

**Comment by berger-n** [comment]
more bizarre here... using Chrome

I have reverted [one commit](https://github.com/buda-base/public-digital-library/commit/fcbb7da0e5b4e884e490fb8ce9337bf88b91628c) and deployed here: http://library-dev.bdrc.io/show/bdr:W3CN22341

- when you click on a volume there is a first bug in the name of "the volume of" property:
![image](https://user-images.githubusercontent.com/33383857/85732087-607be400-b6fb-11ea-864d-94b6704a037f.png)

it works the same whether inspector with "disable cache" is open or not

but...

if you load the page or reload it with inspector open: http://library-dev.bdrc.io/show/bdr:W3CN22341
then close the inspector 
and now click on "volume of" link

- only now you can see the second bug fixed by the commit (wrong label for volume number):
![image](https://user-images.githubusercontent.com/33383857/85733139-3d056900-b6fc-11ea-8f57-0a938d83a9f4.png)

**Comment by berger-n** [comment]
thanks Elie for finding https://www.npmjs.com/package/react-clear-cache
it makes http://library-dev.bdrc.io/ reload itself when build version change has been detected!

yet there may be a (old) minor issue to fix with build directory
we need to configure the built app to be served from a "prod/" directory
so as the app reloads only after build is done and not with error 500 at beginning of build

**Comment by eroux** [comment]
yes, let's do that now so that we can have a fully functioning update system

**Comment by berger-n** [comment]
it works now
http://library-dev.bdrc.io reloads itself after build

before:
![image](https://user-images.githubusercontent.com/33383857/85841206-0b44de80-b79e-11ea-8b19-d8a782c0426b.png)
after:
![image](https://user-images.githubusercontent.com/33383857/85841515-860df980-b79e-11ea-9918-968ec41bcb45.png)

(note that for now it only works on home page at library-dev)

**Comment by eroux** [comment]
ok great! let's deploy it on library and make sure it works on other pages too :)

**Comment by eroux** [comment]
ok, let's close this one too
