### ISSUE TITLE
buggy mirador outline in embedded reader + header

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#179]
The header in 

https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W1ERI0011001&origin=http://dzongsarinstitute.org.in

should not be displayed. Also, when clicking the texts in the outline, nothing happens

**Comment by eroux** [comment]
ah, so in fact it does work, but the link to open the tree is only on the arrow and not on the whole text, it should be on the whole text

**Comment by berger-n** [comment]
nodes open on simple click now instead of double click
regarding the header I've removed the logo but I left breadcrumbs and reduced height a bit ([link](https://library.bdrc.io/scripts/embed-iframe.html?work=bdr:W1ERI0011001&origin=http://dzongsarinstitute.org.in)):

![image](https://user-images.githubusercontent.com/33383857/89200395-406bfa00-d5b0-11ea-8545-92ff5470e781.png)

**Comment by eroux** [comment]
excellent, thanks!
