### ISSUE TITLE
IIIF: open with different viewers

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#24]
It would be interesting to allow the user to open the images with different viewers, such as:
- UniversalViewer
- Mirador
- Diva.js

the main interest of Diva.js is its possibility to display pages in a continuous way and being very minimal (which is good but also has a drawback: it lacks important features)

**Comment by xristy** [comment]
It's nice to be able to switch between UV and Mirador. 

I'm looking forward to seeing whether Diva.js can provide a simple scrolling experience similar to the [internet archive](https://archive.org/details/bdrc-W4CZ57131/page/n1). 

I guess neither UV or Mirador provide out-of-the-box configuration for such scrolling behavior. The scrolling view in Mirador is rather odd to me. 

Both UV and Mirador seem really oriented towards focussing on single image exploration rather than the reading view at internet archive.

**Comment by xristy** [comment]
Thanks. The Diva.js satisfies the scrolling view need. Polishing later should be fine.
