### ISSUE TITLE
Access Restrictions Notification on Records

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#290]
We've been getting inquiries from people who are having trouble accessing restricted texts and are confused because, I think, there isn't a clear indication on the record when a text is restricted. 

I was actually unable to find useful information about restrictions the Record page when I checked, for example, dpe bsdur ma. This is the info I was able to find:
![image](https://user-images.githubusercontent.com/48484924/95347364-cb0bf680-088a-11eb-824f-2eefffc0d27e.png)

A user might read this as meaning they simply need to login to get access, and then think something is broken when they still can't get access.

I think it would be better if it included the restriction symbol that appears on search results and a little more detail (e.g. restricted due to copyright), as we do on tbrc.org:
![image](https://user-images.githubusercontent.com/48484924/95347906-71f09280-088b-11eb-9d32-3d2ff2372979.png)

**Comment by eroux** [comment]
right, I think we should:
- add the icon representing the restriction (fair use or restricted seal)
- update the message with something like:
   * "BDRC only provides restricted access to these images (first and last 20 pages), because the work is advertised as being under copyright" for fair use
   * "BDRC does not provide access the the images of this work because they were provided under the condition that we respect the traditional restriction"

@TBRC-pmench @JannTibetan this could be phrased better by a native speaker of English

**Comment by TBRC-Travis** [comment]
@TBRC-pmench Thanks for bringing this up.  I've also noticed users struggling with this and think we should provide a clearer indication upfront that these are restricted texts.

**Comment by TBRC-pmench** [comment]
> "BDRC only provides restricted access to these images (first and last 20 pages), because the work is advertised as being under copyright" for fair use
BDRC restricts access to this work (only the first and last 20 pages are available online) because the work is under copyright. Please contact help@bdrc.io for information about possibly accessing this work under fair use.

>"BDRC does not provide access the the images of this work because they were provided under the condition that we respect the traditional restriction"
BDRC restricts access to this work because it was provided to BDRC on the condition that we respect traditional restrictions applied to it. If you have received the proper transmission from a spiritual teacher to access this work or have other questions about how to access this work please contact help@bdrc.io.

**Comment by TBRC-Travis** [comment]
Excellent wordsmithing!  I like it.

Also, since we don't have our own lending system in place for copyright texts I would vote for directing people to Internet Archive.  But I know there's been some debate about that.  Ultimately that's where we end up sending people anyway so it would be nice if we could get them there directly through our site.

**Comment by berger-n** [comment]
added the icons and messages: 

- sealed / http://library-dev.bdrc.io/show/bdr:W19567

![image](https://user-images.githubusercontent.com/33383857/95609720-78cffe80-0a5f-11eb-9cee-2e1fbc797abe.png)

---

- fair use / http://library-dev.bdrc.io/show/bdr:IE1PD95844

![image](https://user-images.githubusercontent.com/33383857/95611020-825a6600-0a61-11eb-98b1-c513063e0fa0.png)
---

BTW I found a bunch of bugs while accessing volume content here: http://library-dev.bdrc.io/show/bdr:VL25E4479BEF47D24F
1. etext access is either full when logged or denied (401) when not
2. tries to load images but this is an etext volume
3. each etext resource has number 1 (noticed [here](https://github.com/buda-base/public-digital-library/issues/247))

---

there are other kind restrictions that might need a better notification as well:
- by quality: http://library-dev.bdrc.io/show/bdr:W3CN3014
- temporary: http://library-dev.bdrc.io/show/bdr:W8LS18997

WDYT?

**Comment by eroux** [comment]
Thanks! I think it's good, here are a few suggestions:
- we could use "image" instead of "page", it's a bit more precise, but I don't have a very strong opinion on that
- we could highlight a few words in bold, like "copyright" and "restricts acess", as the text starts to be a bit long...
- we could use a more generic restriction description that would fit restriction by quality, tradition, temporarily and bdrc...

**Comment by berger-n** [comment]
@eroux text is already in semi-bold, so all I can do is underline:

![image](https://user-images.githubusercontent.com/33383857/95746239-c5e9e580-0c96-11eb-8801-b8167c5ae911.png)

![image](https://user-images.githubusercontent.com/33383857/95746349-efa30c80-0c96-11eb-9dd8-bb3bd0f6dfca.png)

**Comment by eroux** [comment]
excellent, thanks!

**Comment by TBRC-pmench** [comment]
For other restrictions (poor quality, embargo, etc.) we can use the very general:

BDRC has restricted access to this work in accordance with our access policies. You can read those policies here: https://bdrc.io/access-policies/.
