### ISSUE TITLE
do not include unsynced / restricted versions by default

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#302]
When searching versions, the default should be to apply the filter "has open" (or something like that). And if there are more results that have restrictions or no image, there should be a message saying "more versions are available, do you want to see them?" with a button that deactivates the filter

**Comment by berger-n** [comment]
hasOpen filter is now activated when starting search on versions: http://library-dev.bdrc.io/search?q=%22gsung%20%27bum%20dri%20med%22&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen
there is also a message when some results are not shown because of it:

![image](https://user-images.githubusercontent.com/33383857/97585660-afaf8980-19f9-11eb-85ee-5e3a314864c1.png)

**Comment by eroux** [comment]
excellent, thanks! can just move the asset "availability block" of the left bar just below the "version type" block?
