### ISSUE TITLE
download button in etexts

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#319]
For all etexts we should have an additional "Download as txt" button on the etext resource page, and at the top of the etext viewer

**Comment by berger-n** [comment]
not sure what you mean here because we already have a download button both:
- on the resource page (and not much space to add another one): 

![image](https://user-images.githubusercontent.com/33383857/98132561-dae41e00-1ebc-11eb-85cb-c2219f523093.png)
---

- on the etext viewer page:

![image](https://user-images.githubusercontent.com/33383857/98132754-11219d80-1ebd-11eb-8ca2-e73fc2344373.png)
---

but I've just added a "Download Etext as TXT" in the download popup for Etext with one volume having one etext resource:
http://library-dev.bdrc.io/show/bdr:IE30037

![image](https://user-images.githubusercontent.com/33383857/98133331-c0f70b00-1ebd-11eb-83c1-2168eab44a43.png)
---

BTW what do you think of https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Disposition ?
we could use `content-disposition` so as the link turns into a download and doesn't opens the text in the browser

next step is to open a volume popup selection for multi-volumes etexts 
but question is what to do with volumes having multiple etext resources ? 
like http://library-dev.bdrc.io/show/bdr:IE1KG14
a subpopup for each volume etext resources? or maybe build a zip for the whole volume?

**Comment by eroux** [comment]
Ah yes, excellent idea about content-disposition!

For the resource page, let's not create a popup with all the volumes like we do for PDFs, let's instead:
- focus on https://github.com/buda-base/public-digital-library/issues/330
- create an API to generate a .zip file with all the txt files in a resource, it's probably best... I'll open a separate issue for that

For the download button, I think the reason I wanted to have an additional button on the resource page is because I think the Download button is too discreet... but yes, adding a new button won't fix that problem, sorry for that.

Overall I think it's good as it is, thanks!
