### ISSUE TITLE
facet on associated century

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#335]
I'll implement a new property `tmp:assocCentury` on persons, and will return that same property in results in:
- persons
- works
- versions
- etexts

(in a first iteration it will just return the value of the author).

It won't be something to display (in the results nor in the resource page), but it can be used in the facets. The value will just be an integer which is the century number minus 1 (for instance 1750 will have `tmp:assocCentury 17`). There needs to be changes in several repositories before this can be implemented on the client but let's track it there.

**Comment by eroux** [comment]
Ok, the data is ready (not on Fuseki yet so that it doesn't disturb the app), now let's start with the persons search. The property is named `tmp:associatedCentury` and contrary to the initial intent, it records the actual century (ex: 1750 -> associatedCentury 18). I'm not sure how best to display the centuries in the facets, maybe something like `13th c.`? (there must be a way to get the `th` from a js library).

In Tibetan: `དུས་རབས་ ༡༠` (or `དུས་རབས་བཅུ་པ།`) for the 10th century.

**Comment by berger-n** [comment]
it seems to work fine: http://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Person&s=popularity&pg=1&f=century,inc,13

![image](https://user-images.githubusercontent.com/33383857/99288673-42468a00-283c-11eb-80ca-9ee38ee274c8.png)
---

in tibetan: 

![image](https://user-images.githubusercontent.com/33383857/99288785-6a35ed80-283c-11eb-8e3f-9d9a61eb832b.png)

---

also something related to https://github.com/buda-base/public-digital-library/issues/307 and the order of values in facet widgets 
it seemed quite straightforward here to have centuries sorted chronologically:

![image](https://user-images.githubusercontent.com/33383857/99289063-c26cef80-283c-11eb-86bc-2a9a5b0732fe.png)

(actually there was some sort of javascript bug with maps that prevented the usual sort to work - had to insert a space [here](https://github.com/buda-base/public-digital-library/commit/6a33ddf71edfadfbef7cd74783ff5ad7f1da975e#diff-625c313db761131d9ad6a6782ab9f54dddefdf30bd85fbe78cd98a686768f218R1287) so that the insertion order in map would be kept as usual and not lost because key is a number, even casted to string)

so now it seems quite straightforward to have a given facet' values sorted in a custom way, if you want to!

**Comment by berger-n** [comment]
BTW function to add ordinal suffix to numbers is [here](https://github.com/buda-base/public-digital-library/commit/6a33ddf71edfadfbef7cd74783ff5ad7f1da975e#diff-99acca0e99f2c9762a8880aa24af09136368b0b55234a1971e17963d6c4c07feR22)
(taken from https://stackoverflow.com/questions/13627308/add-st-nd-rd-and-th-ordinal-suffix-to-a-number#answer-57518703)

**Comment by eroux** [comment]
great, thanks a lot! Chronological is better yes, probably with the most recents at the top... also in case there's no century associated with a person, is there an "unknown" button?

**Comment by eroux** [comment]
Ok, I've added the property on works, instance and etext search. For these the label of the facet should be "Author's century" not just "century" (otherwise it could be confused with the century of the creation of the physical instance)

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22dalai%20lama%22&lg=en&t=Instance&pg=1&f=asset,inc,tmp:hasOpen&f=century,inc,unspecified

![image](https://user-images.githubusercontent.com/33383857/99379935-9481bc80-28c9-11eb-8f75-a1cbf18b2f06.png)

**Comment by eroux** [comment]
looks perfect, thanks a lot!
