### ISSUE TITLE
change default message when the library reloads because of an update

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#342]
When a user opens their browser on a resource page and a new version of the app is available, there's a message saying "resource xxx is not available, redirecting...", which is incorrect because once the app reloads, the resource is displayed

**Comment by berger-n** [comment]
I can't reproduce this

if the library needs to reload and does so, what I see is that it just stops everything and fades to white like a regular reload, then opens the page again

to me the "resource not available, redirecting" happens when ldspdi is restarting after an update and library has failed fetching resource data ([code](https://github.com/buda-base/public-digital-library/blob/c2decf932dd6f32a4302ae1bc43ed4a62c23be0d/src/components/ResourceViewer.js#L6289))

**Comment by eroux** [comment]
hmm ok, I reproduced it quite frequently. This would be the case for instance if:
- the app is redeployed
- the user goes to http://library.bdrc.io/show/bdr:WA4CZ16799 directly (without going through the home page)

I'll see if I can reproduce it on library-dev by redeploying

**Comment by eroux** [comment]
(hmm, right, I can't reproduce it now... maybe it's some sort of weird interaction between the cache of the browser and the app...)

**Comment by eroux** [comment]
Well, I'll see if I can reproduce it later, let's close this for now
