### ISSUE TITLE
crash on etext viewer

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#351]
the app crashes when opening an etext, see https://library.bdrc.io/show/bdr:UT1KG4884_001_0001#open-viewer

**Comment by berger-n** [comment]
fixed
yet the etext has nothing to show because it is said to have pages [here](http://purl.bdrc.io/query/graph/Etext_base?I_LIM=500&R_RES=bdr%3AUT1KG4884_001_0001&format=json)
but they are not returned [here](http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUT1KG4884_001_0001&I_START=0&I_END=10000) as expected ([working example](http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUTIE0OPP000301_v010&I_START=0&I_END=10000))

**Comment by eroux** [comment]
ah yes, thanks, I'll fix that in the migration

**Comment by berger-n** [comment]
perfect! thanks
