### ISSUE TITLE
etext size in Mirador is wacky again

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#361]
now it's tiny on https://library.bdrc.io/show/bdr:W1PD100944, see this screenshot:

![Capture d’écran de 2020-11-18 20-54-30](https://user-images.githubusercontent.com/60868/99581344-f08b3480-29e0-11eb-809e-26d0bf48147d.png)

I think at some point we had a sensible, fixed font size but now we're back to the font size that changes with the screen size... is there a reason we went back to that?

**Comment by berger-n** [comment]
I'm not sure what the problem is with using a font size related to image size 
compare with what it looks like if we don't:
- variable size, max zoom:

![image](https://user-images.githubusercontent.com/33383857/99641437-8ad39280-2a4a-11eb-964d-86331cfeaab3.png)

- fixed size, max zoom:

![image](https://user-images.githubusercontent.com/33383857/99641512-ab9be800-2a4a-11eb-8bb1-f95f1682591f.png)

I thought the latter was barely usable so I reverted to variable size
which did not seemed an issue because even fixed size text depends on screens size here...
as everything is scaled so that the largest image has window width
compare:
- fixed font size, ~1280px width window:

![image](https://user-images.githubusercontent.com/33383857/99642272-9a9fa680-2a4b-11eb-966d-552e3a01a31a.png)

- fixed font size, ~1700px width window:

![image](https://user-images.githubusercontent.com/33383857/99642439-cf136280-2a4b-11eb-9c34-4b4cf27abe33.png)

if what you want is fixed font size not depending on zoom level nor window width (like page numbers) CSS/responsive is of no use here but I can try something with javascript (crossing fingers it won't make changing zoom level too slow but let's try it first!)

**Comment by eroux** [comment]
oh I see, so the problem is that the zoom level scales the images and the text... is there a way the zoom could make only the images bigger?

**Comment by berger-n** [comment]
there is a trick that is used with page numbers: we zoom them out by the same factor the whole div is zoomed in
I think we could use that for text but it might not be straightforward as it messes with regular html alignment flow
(I mean re-zoomed text will not fit in gray area, for example) 
but I have some ideas to fix that
I'll give it a try

**Comment by eroux** [comment]
ah great, thanks!

**Comment by eroux** [comment]
if the grey background is a problem we can imagine removing it, the text has its own background already

**Comment by berger-n** [comment]
some progress here: http://library-dev.bdrc.io/view/bdr:I1PD106519
etext font size does not change with window width or zoom level:

- width 1280px, zoom auto:

![image](https://user-images.githubusercontent.com/33383857/99819052-41b93680-2b4f-11eb-807c-88376fb55396.png)
---

- width 1920px, zoom auto:

![image](https://user-images.githubusercontent.com/33383857/99819232-804ef100-2b4f-11eb-8649-53071628c685.png)
---

- width 1920px, zoom 100%:

![image](https://user-images.githubusercontent.com/33383857/99819337-a2487380-2b4f-11eb-81b8-93f8755cd803.png)
---

good thing is it's invisible/fast when zooming in/out or changing window size!

now something to think about is font size relative to tibetan unicode content or not
some pages are mixed so it uses latin text font size:

![image](https://user-images.githubusercontent.com/33383857/99819811-39153000-2b50-11eb-8ec2-3058b27275b7.png)

I'll need a better test to detect wich size to use (for now it only looks for one latin caracter in page to set font size to "not tibetan")

another thing to fix is zooming in/out while keeping current image in view (things are a bit broken here because the scroll update computation needs to include these new "constant height" areas...)

**Comment by eroux** [comment]
ah yes, this is excellent, thanks a lot!! Don't spend too much time on the zooming in/out while keeping the same image on screen if it's difficult, it's already pretty good! we can keep that for later

For the non-Tibetan size, what about doing the opposite text: if there's one Tibetan Unicode character we switch to the Tibetan font size?

**Comment by berger-n** [comment]
seems good to me now

**Comment by eroux** [comment]
yes, this is great, thanks a lot!
