### ISSUE TITLE
bug when trying to open LOC manifest when logged

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#374]
see https://library.bdrc.io/show/bdr:W0LOC0001

**Comment by eroux** [comment]
a recent commit made things work when unlogged, but mirador sends a token when I'm logged, and apparently this is a problem for the LOC, or at least in the interaction with Firefox

**Comment by berger-n** [comment]
not sure the fix is the best one but it works
the problem is/was fetching https://iiifpres.bdrc.io/vo:bdr:I0LOC0001/manifest leads to a 302 redirection:

![image](https://user-images.githubusercontent.com/33383857/100461067-85b8b800-30c8-11eb-963a-b914cd73c2ee.png)

current fix tests for RID matching `bdr:...LOC...` and doesn't send token if it's the case

**Comment by eroux** [comment]
oh, hmm... not an easy problem indeed... maybe what could be done is to ask Javascript not to follow redirects (if it's possible?) and then do the redirect by hand but without the token?

**Comment by berger-n** [comment]
I was hoping https://javascript.info/fetch-api#redirect would help
but actually it doesn't because as stated by https://fetch.spec.whatwg.org/#atomic-http-redirect-handling in https://github.com/whatwg/fetch/issues/763#issuecomment-397254891 :

> redirects  are not exposed to APIs. Exposing redirects might leak information not otherwise available through a cross-site scripting attack. 

after running a few tests it seems we can only prevent fetch to follow 302, but not get which url we're being redirected to...

**Comment by eroux** [comment]
ah hmm... well... interesting issue... not much more we can do indeed! Thanks for the investigation!

**Comment by berger-n** [comment]
just noticed it's the same for Taisho manifests: https://library.bdrc.io/show/bdr:W0SATT0400
viewer won't open if user is logged... don't we need to display a warning or something?
there may be some test to do client-side to prevent sending token to iiif server
which would be harmless when things are open access like these
(I'm thinking about checking the RID but I guess you won't like it ^^)

**Comment by eroux** [comment]
Well, unfortunately I can't find any solution other than checking the RID... so yes let's do that! Everything starting with:
- `[WI]0SAT`
- `[WI]EAP`
- `[WI]0CDL`
- `[WI]0IA`
- `[WI]0SBB`
- `[WI]0LOC`
- `[WI]0LULDC`

shouldn't be called with a token
