### ISSUE TITLE
very slow outline rendering

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#387]
it may be a flaw in the way this part of the data is handled, but just in case we can do some optimizations in the code to make it run better, https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_2741 is very slow

**Comment by berger-n** [comment]
some improvement here:
- loading in almost 40sec, with node details showing/hiding in around 5sec: https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_2741
- loading in less than 15sec,  with details showing/hiding in less than a sec: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_2741

![Screenshot_20210910_172349](https://user-images.githubusercontent.com/33383857/132878041-bcfbcc66-cfa7-44d3-a7f1-978451ece6d3.png)

![Screenshot_20210910_172617](https://user-images.githubusercontent.com/33383857/132878370-09fa02cf-b309-4ebf-9c22-f27bea7d56ee.png)

some fixes are needed in outline search now: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1124&osearch=%22sku%20gsum%20la%20bstod%22~1@bo-x-ewts
(display results when loading page + showing/navigation in siblings)

**Comment by eroux** [comment]
great! well, the issue is now clearly on the query side... but it seems ldspdi-dev doesn't send gzipped results, hence the very long time, I'll change that so that we get more realistic results.

The mechanism I initially had in mind was the following though:
- when there are more than X subnodes: 
- take the first node and look at the volume number, take the last node and look at eh volume number
- if they are different, create a new hierarchy where all texts are organized by volume number, just labelled "volume x"

do you see what I mean?

**Comment by eroux** [comment]
BTW, I think we lost the spinner when the outline loads? at least on firefox. I think we can deploy (in prod) the optimizations that only change performance, perhaps we should make the changes in the display in a branch?

**Comment by eroux** [comment]
here's a request to get the parts of an instance in a certain volume:

http://ldspdi.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW23703_S0002&I_VNUM=3

also now

http://ldspdi.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW23703 now returns

`tmp:hasNonVolumeParts = true`. So the algorithm would be something like:

- before we get the subparts of a node (for instance `MW23703_S0002`), if the node has a content location spanning more than one volume (which is the case here) and has `tmp:hasNonVolumeParts = true`, instead of fetching the parts through outline_root, we just display the list of volumes of the content location (volume 2, volume 3, etc.), and when the user clicks on a volume, we fetch the subnodes through `Outline_root_pervolume`. Could that work @berger-n ? If so, perhaps let's revert the last commit so that this change is more simple

**Comment by berger-n** [comment]
some good progress here: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1148

noticed a few bugs/unexpected things in queries though:
- https://library-dev.bdrc.io/show/bdr:MW12827#outline is not working anymore, I guess it has to do with [query on volume](https://ldspdi-dev.bdrc.io/query/graph/Outline_root_volumes?R_RES=bdr%3AMW12827_BB8776) not returning all that is needed compared to [bdr:MW23703_S0001](https://ldspdi-dev.bdrc.io/query/graph/Outline_root_volumes?R_RES=bdr:MW23703_S0001)
- regarding `tmp:firstImageGroup` it's not what I was expecting because it's same for each volume...  compare https://ldspdi-dev.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW23703_S0002&I_VNUM=2 and https://ldspdi-dev.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW23703_S0002&I_VNUM=3 in both it's `bdr:I1318` nut I was expecting `bdr:I1318` and `bdr:I1319`... thus when you open some text in Volume 10 http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1264 it thinks that it's bdr:I1318 / Volume 2:

![Screenshot_20210911_194041](https://user-images.githubusercontent.com/33383857/132956512-eaffd8fb-549f-4ece-a1f1-bf243f319069.png)

**Comment by eroux** [comment]
thanks a lot that's great! just fixed the query

**Comment by eroux** [comment]
I think we can deploy this, this is a huge improvement

**Comment by berger-n** [comment]
not sure about deploying because of http://library-dev.bdrc.io/show/bdr:MW12827#outline
which is not working at all anymore and even crashing if you open section 2 / subsection 2...

**Comment by eroux** [comment]
Oh right yes sorry, you're right

**Comment by berger-n** [comment]
a fix for opening current node in a volume when loading page: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1570

![Screenshot_20210913_122522](https://user-images.githubusercontent.com/33383857/133068001-dd427dff-db78-494f-8e8d-bae8b4d902e9.png)
---

regarding http://library-dev.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_93EB9C it's better but not fixed

![Screenshot_20210913_122842](https://user-images.githubusercontent.com/33383857/133068441-3b5192b9-5446-49b8-ae9f-4451ccb6c095.png)

for readability let's say that 
section *bla ma yang tig (e)* is `MW12827_93EB9C`
volume *pod dang po/ bla ma yang tig (e)* is `MW12827_602352`)

then here in [`Outline_root` query on `MW12827_93EB9C`](http://ldspdi-dev.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW12827_93EB9C) it says:

![Screenshot_20210913_122630](https://user-images.githubusercontent.com/33383857/133068140-543a90a1-1ea3-497d-82aa-0d1c2fb2ae51.png)



but in [`root_pervolume` query for `MW12827_602352`](http://ldspdi-dev.bdrc.io/query/graph/Outline_root_pervolume?R_RES=bdr%3AMW12827_602352&I_VNUM=1) there is no `hasPart` for the main node:

![Screenshot_20210913_122806](https://user-images.githubusercontent.com/33383857/133068356-0faf4b40-45d9-4f1f-9fa7-61baffc73f4d.png)

**Comment by berger-n** [comment]
keeping track of things:
- [ ] opening section node bypasses the `_pervolume` thing: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_S0002
- [ ] opening image group as node doesn't open node in outline when loading page: http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:I1318
- [ ] opening image group record dispays its content as outline: http://library-dev.bdrc.io/show/bdr:I1318
  @eroux let's remove it?
  ![Screenshot_20210913_130305](https://user-images.githubusercontent.com/33383857/133072732-25bbc56c-7a79-4abc-98f2-c2520106c26a.png)

**Comment by eroux** [comment]
the third feature is actually kind of cool...

**Comment by eroux** [comment]
hmmmm something I don't understand: if in the query about [MW12827_93EB9C](http://ldspdi-dev.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW12827_93EB9C) it says it has non-volume nodes, why do you use `Outline_root_pervolume` on it and not just `Outline_root` ? (I don't think you should in that case)

**Comment by berger-n** [comment]
bdr:MW12827 is now fine again! http://library-dev.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_13A94A

**Comment by berger-n** [comment]
opening http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_S0002 is now fine:

![Screenshot_20210913_142407](https://user-images.githubusercontent.com/33383857/133082796-9d4d69bf-642f-47b7-8c6f-23c8c3291d88.png)

**Comment by berger-n** [comment]
I've made links to image groups usable (right click / open in other tab): https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_S0002

![Screenshot_20210913_170023](https://user-images.githubusercontent.com/33383857/133107691-4930caad-6828-41a7-b4be-b2d3f619bbb1.png)
---

regarding outline in image groups page, alas it's a side effect when you have opened the node in outline then go to record...
is that really a feature we need? if so we might think of implementing it (though it might requiring adding some data here or there)

**Comment by eroux** [comment]
no need to look at this now, it's working well enough, but let's also handle https://library.bdrc.io/show/bdr:MW2KG5015?part=bdr:MW2KG5015_4061 that doesn't display per volume

**Comment by berger-n** [comment]
everything's back to ok now:
https://library.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_891768
https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1862
https://library.bdrc.io/show/bdr:MW0TT0000?part=bdr:MW0TTT0039
https://library.bdrc.io/show/bdr:MW2KG5015?part=bdr:MW2KG5015_4061

need to fix https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_2503 now 
which won't show on load (because it's beyond the 40 items displayed in its parent)

**Comment by eroux** [comment]
excellent, thanks!!

**Comment by berger-n** [comment]
fixed centering open node in volume/text list: 
- https://library.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_2503

![Screenshot_20210914_153955](https://user-images.githubusercontent.com/33383857/133268502-ec8a3db8-b1e3-4591-a22e-e37e821ce5b7.png)

- https://library.bdrc.io/show/bdr:MW0TT0000?part=bdr:MW0TTT0073

![Screenshot_20210914_154429](https://user-images.githubusercontent.com/33383857/133268950-f285b5f9-9f3a-4bc4-ae8a-99e16c6b5ac5.png)
---

fixed wrong query opening chapter in `MW12827` as well: https://library.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_EB30FA

**Comment by eroux** [comment]
wonderful!

**Comment by berger-n** [comment]
keeping track of a bug here: https://library.bdrc.io/show/bdr:MW1KG14?part=bdr:MW1KG14_35A20E

![Screenshot_20210917_180049](https://user-images.githubusercontent.com/33383857/133818855-c7549ae8-5679-4927-a7f5-22581269c8ad.png)
---

something I didn't expect is that a given volume ([Volume 4 / `bdr:I1KG19`](https://library.bdrc.io/show/bdr:I1KG19) here) can be subnode of multiple sections, half a dozen of subsections of https://library.bdrc.io/show/bdr:MW1KG14?part=bdr:MW1KG14_B9C8E4 actually, with [query](https://purl.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW1KG14_B9C8E4) having `partType = bdr:PartTypeSection` and `tmp:hasNonVolumeParts = true` for each of them:

![Screenshot_20210917_180550](https://user-images.githubusercontent.com/33383857/133819485-1bfeeca2-01d9-4ab0-a954-82bbca4c7631.png)
 
is this intended?

not sure how to handle that because volume id / image group number is used as key for its own outline data
resulting here in duplicating/erasing information : 
 
![Screenshot_20210917_181341](https://user-images.githubusercontent.com/33383857/133820449-2f8e583a-4019-40a7-9f23-18d389638887.png)

**Comment by eroux** [comment]
ah no, that's totally intended, a volume can be in several sections, and a text can be in several volumes... I'm not sure how best to resolve that... is it feasible on the client to create keys like `bdr:MW23703_S0001__bdr:I9876` ? Or should I create identifiers in the query? (it's possible, but then the identifiers won't lead anywhere). Or perhaps blank nodes?

**Comment by berger-n** [comment]
fixed: http://library-dev.bdrc.io/show/bdr:MW1KG14?part=bdr:MW1KG14_30AD59

![Screenshot_20210927_175739](https://user-images.githubusercontent.com/33383857/134943368-95b33538-c43a-4db5-8cbe-c3a079e447bb.png)
---

and everything else still seem to be fine:
http://library-dev.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_891768
http://library-dev.bdrc.io/show/bdr:MW23703?part=bdr:MW23703_1862
http://library-dev.bdrc.io/show/bdr:MW0TT0000?part=bdr:MW0TTT0039
http://library-dev.bdrc.io/show/bdr:MW2KG5015?part=bdr:MW2KG5015_4061
http://library-dev.bdrc.io/show/bdr:MW4CZ45313?part=bdr:MW4CZ45313_0058-1
http://library-dev.bdrc.io/show/bdr:MW1PD96684?part=bdr:MW1PD96684_0781

**Comment by eroux** [comment]
excellent, thanks!

**Comment by berger-n** [comment]
node not opening when loading page: http://library-dev.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_8B26FD

![Screenshot_20211006_165006](https://user-images.githubusercontent.com/33383857/136227777-7621304b-e003-448b-9a0b-bb040af0fa06.png)

**Comment by eroux** [comment]
oh that's bad... what's happening here?

**Comment by eroux** [comment]
it seems that ldspdi-dev.bdrc.io/query/graph/Outline_root?R_RES=bdr%3AMW12827_8B26FD&format=ttl (which is the first thing called by the page) is correct: 

```ttl
bdr:MW12827_FD02F6  skos:prefLabel
      "sangs rgyas kyi 'das rjes gsum:"@bo-x-ewts ;
   bdo:hasPart   bdr:MW12827_01A3F4 , bdr:MW12827_0996E2 , bdr:MW12827_8B26FD ;
   bdo:partIndex  2 ;
   bdo:partTreeIndex  "2.1.6.2" ;
   bdo:partType  bdr:PartTypeChapter ;
   tmp:hasNonVolumeParts  true .
```

so I'm not sure why the JavaScript is calling http://ldspdi-dev.bdrc.io/query/graph/Outline_root_volumes?R_RES=bdr%3AMW12827_FD02F6

**Comment by berger-n** [comment]
indeed, thanks! problem fixed: http://library-dev.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_8B26FD

![Screenshot_20211006_171711](https://user-images.githubusercontent.com/33383857/136232850-ef81c3f8-76f9-4eb8-aa53-778ee01f1463.png)

**Comment by eroux** [comment]
seems fixed, let's close this
