### ISSUE TITLE
advanced query syntax

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#390]
a (surprisingly) common use case / feedback from the students we're going to give a demo to tomorrow is the following: it would be used for to search `"term1"  and  "term2"` instead of `"term1 term2"` like we do now. Interestingly this is already possible in our current architecture! Except in the UI. For instance to search *zhi ba* and *lha*, the Lucene query is `("zhi ba" AND "lha")` and it actually works directly when such a query is put in the URL, for instance:

https://library.bdrc.io/search?q=(%22zhi%20ba%22%20AND%20%22lha%22)&lg=bo-x-ewts&t=Person

(see result number 3 "lha zhi ba 'od", not found in the "zhi ba lha" query). The problem is that trying to do that in the query bar doesn't work as the UI removes the quotes and lower cases the `AND` which should absolutely be kept upper case).

i'm not sure what the best solution is though... maybe an "advanced search" checkbox on the right which modifies the behavior of the search bar... or maybe a "multiple search" (or just "Add term" button) that adds another search bar beneath with the label "AND" on the left, and with the lang tags synchronized... let's think of this a bit more

**Comment by xristy** [comment]
Adding a type of _advanced query_, maybe **direct**, would be a great solution, rather than attempting some sort of query by example, or UI query constructor. There's documentation on what sort of queries can be written:

[Queries with _Boolean Operators_ and _Term Modifiers_](https://jena.apache.org/documentation/query/text-query.html#queries-with-_boolean-operators_-and-_term-modifiers_)

so that would be a nice help to those users who are interested in more refined control. The main thing would be that users need to be aware of the one triple == one document model used in Fuseki.

At some point I suppose one could open up the possibility of the user providing an entire set of query input arguments from the search input in the UI so as to allow for property lists and limits.

**Comment by eroux** [comment]
Yes, I agree it would be a good solution, we could even write our own very simple documentation... For me the main problem of this solution is that it's error prone, and if users write "and" instead of "AND", which I'm quite sure many users will, it will create an "or" query with the two terms plus the term "and" and it will be super slow (I actually made the mistake a few times and the queries take forever)... At least if there's a UI we can prevent that

**Comment by xristy** [comment]
I think I can put together a small doc on the query syntax that can be used. 

`Single Terms` and `Phrases` are the basis of Lucene's syntax. A pre-pass can normalize the user's input to upcase the `Boolean Operators`. Since the operators are: `OR`, `AND`, `NOT`, `+`, and `-`; I don't think any of them can be expected to be used as a term. 

The normalization should treat phrases as opaque so if there is some need to use one of the operators as a term wrapping it in double quotes would suffice.

When in direct/advanced mode the user input needs to be wrapped in parentheses, `(` and `)`, versus wrapping the input in double quotes.

I'm thinking of _direct_ as a mode of a general _advanced search_ since there may be other forms of advanced search that may be contemplated in the future.

The syntax will not include explicit `Field` references such as `preLabel:"mdzod bdun"` since the fielding is provided by the context in which the search is performed and would require rather an intimate knowledge of the internals of the Lucene config and ontology.

I think wildcard searches probably don't work unless the buda analyzers handle `?` _single char wildcarding_, e.g., `mdz?d`, and `*` _multiple char wildcarding_, e.g., `bod*va`.

I don't think the limited Lucene _regular expression_ mechanism is likely to work with the buda analyzers.

The _fuzzy_ search support also needs analyzer support which I doubt is implemented:

> Lucene supports fuzzy searches based on Damerau-Levenshtein Distance. To do a fuzzy search use the tilde, "~", symbol at the end of a Single word Term. For example to search for a term similar in spelling to "roam" use the fuzzy search:
>
>    `roam~`
>
> This search will find terms like foam and roams.

`Proximity Searches` can be included such as `"tshig don mdzod"~5` will find occurrences of `tshig don rin po che'i mdzod`

```
prefix text: <http://jena.apache.org/text#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select *
where {
  (?s ?sc ?lit ?g ?p) text:query (skos:prefLabel "(\"tshig don mdzod\"~5)")
}
```

_Term Boosting_ is not useful for this application I think.

**Comment by xristy** [comment]
So here is a doc for advanced search syntax:

[BUDA_Library_Advanced_Search.md.zip](https://github.com/buda-base/public-digital-library/files/5681412/BUDA_Library_Advanced_Search.md.zip)

There are two points:
- the queries should be _normalized_ by upcasing word occurrences of: AND, OR, and NOT
- I think that a use of the advanced search syntax could signaled by simply surrounding the query with outer parentheses without having to use a checkbox or button or whatever.

I.e., if the user enters:
```
("dri med" not "'od zer")
```
in the search box, then that should be sufficient to signal that it is an advanced query and just needs to be fed to the `text:query` in the _query string_ position, as is after normalization. So this example would have a query like:
```
(?s ?r ?lit) text:query ( skos:prefLabel "(\"dri med\" NOT \"'od zer\")" "highlight:" )
```
Since the query string passes through a SPARQL text, the inner occurrences of double quotes will need to be escaped during normalization.

**Comment by eroux** [comment]
Before we can move on with that there are a few considerations that could be implemented first:
- this means that we won't have just one keyword but potentially several, so all the functions that highlight things on the client (I think it's used in a few places as a fallback mechanism) should take a list of strings instead of a string
- the lucene to keyword function should return a list of strings instead of a string (for now it can be just putting the keyword in a list that would just contain it)
- the lucene to display function (for the breadcrumbs, title, etc.) should also be adapted so that it handles queries like `("X"~1 AND "Y")@en` and output something like `"X" AND "Y"`, so it can be just removing the parenthesis and the `~1` possibly. It should also be the function that handles the search bar, let's call it lucene2input, with a reverse function input2lucene. The first implementation can just handle the current things

Once it's done we can change the UX, search bar, etc. easily. I can make new functions that implement all that so that we can implement the new search mechanisms. It's not the highest priority

**Comment by berger-n** [comment]
you can now use `AND` keyword in search bar: http://library-dev.bdrc.io/search?q=(%22zhi%22%20AND%20%22ba%22%20AND%20%22lha%22)&lg=bo-x-ewts&t=Person

highlighting works in expanded etext context but only in other matches for now:

![image](https://user-images.githubusercontent.com/33383857/107553341-f43fe900-6bd4-11eb-967a-be788f24fe2e.png)

**Comment by eroux** [comment]
oh, wonderful!!

**Comment by eroux** [comment]
here's a bug: I type dang po AND sangs rgyas in the search bar on library-dev, and it leads me to

http://library-dev.bdrc.io/search?q=(%22%22dang%20po%22%20AND%20%22sangs%20rgyas%22%22)&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen

with too many quotes, it should be

http://library-dev.bdrc.io/search?q=(%22%22dang%20po%22%20AND%20%22sangs%20rgyas%22%22)&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen

**Comment by berger-n** [comment]
everything seems ok with highlighting now, both in results and etext viewer:

![image](https://user-images.githubusercontent.com/33383857/107672050-c6ba7480-6c94-11eb-83d0-ac97d09227cb.png)
--

![image](https://user-images.githubusercontent.com/33383857/107672871-b1921580-6c95-11eb-9cd2-eda4ee5d9fbb.png)


---

with transliterated text as well: 

![image](https://user-images.githubusercontent.com/33383857/107673092-ef8f3980-6c95-11eb-8707-32dd799f97e6.png)
--

![image](https://user-images.githubusercontent.com/33383857/107673433-4ac12c00-6c96-11eb-9021-111e5454e6a8.png)

**Comment by eroux** [comment]
wonderful, thanks a lot! I think we can deploy!

**Comment by berger-n** [comment]
(it's now deployed on https://library.bdrc.io/)
