### ISSUE TITLE
don't display translationOf property in work results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#423]
An example: https://library.bdrc.io/search?q=%22thar%20mdo%22&lg=bo-x-ewts&t=Work

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/106871253-57f87c80-66d2-11eb-99ec-cb4bf60131be.png)

**Comment by eroux** [comment]
thanks! interesting display of the Mongolian Unicode... :)

**Comment by berger-n** [comment]
- don't know if this is related: https://library.bdrc.io/show/bdr:WA0RK0264

![image](https://user-images.githubusercontent.com/33383857/106872006-2502b880-66d3-11eb-922e-68042461bd2e.png)

(there is a legacy `hasTranslation` label hidden before `WA0TTT2871`)

hadn't `hasTranslation` been replaced by `hasParallelsIn`? what to do here?
I've noticed there is no label for `WA0TTT2871` in [query](https://purl.bdrc.io/query/graph/ResInfo-SameAs?R_RES=bdr%3AWA0RK0264&format=json)

- regarding mongolian font should we do something? my system has no font to display it but maybe we could load a fallback one when used (yet it would be used instead of user installed system font for mongolian)
WDYT?

**Comment by eroux** [comment]
We now have both workHasTransalation (/ workTranslationOf) and workHasParallelsIn, the former being quite rare. WA0TTT2871 is an error in the data, it will be fixed tomorrow

**Comment by berger-n** [comment]
ok! looks better now:

![image](https://user-images.githubusercontent.com/33383857/106878356-27b4dc00-66da-11eb-81a5-04a0381248bc.png)

**Comment by eroux** [comment]
Thanks! Now it's less ideal in https://library.bdrc.io/show/bdr:WA0TTET0262 though... but let me make a new migration, this hasTranslation is really a typo, the correct thing is what's on https://library.bdrc.io/show/bdr:WA0TTET2871, so perhaps we should have let the label hidden?

**Comment by berger-n** [comment]
ok you're right, I've reverted my fix as this was a typo in data
