### ISSUE TITLE
prefLabel on search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#439]
this is contiguous to the previous issue, but even when there's a match in a prefLabel of a sameAs, it would be best to only use the prefLabel of the BDRC entity, and display the match on the prefLabel of the sameAs as a variant name / variant title. For instance in

https://library.bdrc.io/search?q=%22sgam%20po%20pa%22~1&lg=bo-x-ewts&t=Person

the first match should be:

```
bsod nams rin chen  (in bold)
variant label: [sgam po pa] bsod nams rin chen  ([] is the highlight)
```

**Comment by eroux** [comment]
related issues: https://github.com/buda-base/xmltoldmigration/issues/170 https://github.com/buda-base/public-digital-library/issues/438

**Comment by berger-n** [comment]
for now data from query won't allow trying anything client-side: http://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22sgam%20po%20pa%22~1

```
{
  "xml:lang": "en",
  "type": "http://www.w3.org/2004/02/skos/core#prefLabel",
  "value": "Gampopa Sonam Rinchen"
},{
  "xml:lang": "en",
  "type": "http://www.w3.org/2004/02/skos/core#prefLabel",
  "value": "Gampopa"
},...,{
  "xml:lang": "bo-x-ewts",
  "type": "http://purl.bdrc.io/ontology/tmp/nameMatch",
  "value": "↦sgam po pa↤ bsod nams rin chen/"
},...,{
  "xml:lang": "bo-x-ewts",
  "type": "http://www.w3.org/2004/02/skos/core#prefLabel",
  "value": "sgam po pa bsod nams rin chen/"
},...,{
  "xml:lang": "zh-hani",
  "type": "http://www.w3.org/2004/02/skos/core#prefLabel", 
  "value": "岡波巴"
},...,{
  "xml:lang": "bo-x-ewts",
  "type": "http://www.w3.org/2004/02/skos/core#prefLabel",
  "value": "bsod nams rin chen/"
},
```

that being said there doesn't even seem to be a straightforward solution to "tag" these prefLabel with their origin...
maybe add BDRC resources with their `prefLabel`s in `aux` so that client can test if a given matching label is from an external source or not? wdyt?

**Comment by eroux** [comment]
oooh, you're totally right, I overlooked that sorry! let me think of a solution

**Comment by eroux** [comment]
here's an attempt: http://purl.bdrc.io/lib/personGraph-sameAs?LG_NAME=bo-x-ewts&L_NAME=%22sgam%20po%20pa%22~1 would that work?

**Comment by berger-n** [comment]
done: http://library.bdrc.io/search?q=%22sgam%20po%20pa%22~1&lg=bo-x-ewts&t=Person

![image](https://user-images.githubusercontent.com/33383857/110971714-80236d00-835b-11eb-9414-00f95ad8f59f.png)

**Comment by eroux** [comment]
excellent, thanks a lot!

**Comment by eroux** [comment]
result number 15 on this search is a little suspicious... https://library.bdrc.io/search?q=%22blo%20gros%20brtan%20pa%22~1&lg=bo-x-ewts&t=Person

**Comment by berger-n** [comment]
I think it's better now: https://library.bdrc.io/search?q=%22blo%20gros%20brtan%20pa%22~1&lg=bo-x-ewts&t=Person

![image](https://user-images.githubusercontent.com/33383857/111176103-5495c200-85a9-11eb-930a-d0609edca193.png)

note that it's now ranked 3 based on popularity which seems correct according to [query](http://purl.bdrc.io/lib/personGraph?LG_NAME=bo-x-ewts&L_NAME=%22blo%20gros%20brtan%20pa%22~1)
(it was't the case before because the actual result is https://sakyaresearch.org/persons/1537 
and data corresponding to its BDRC `sameAs` P4CZ16794 wasn't properly used so far)

this place search also works fine now: https://library.bdrc.io/search?q=%22rtse%20pho%20brang%20po%20tA%20la%22~1&lg=bo-x-ewts&t=Place&s=place%20name

![image](https://user-images.githubusercontent.com/33383857/111177389-75124c00-85aa-11eb-8448-a6111840e2c2.png)

(`prefLabels` for `bdr:G2800` seem to be missing from [query](https://purl.bdrc.io/lib/placeGraph?LG_NAME=bo-x-ewts&L_NAME=%22rtse%20pho%20brang%20po%20tA%20la%22~1) though)

**Comment by eroux** [comment]
great, perfect!! thanks
