### ISSUE TITLE
warning for third party images / manifests

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#44]
Apparently some extensions (such as [Privacy Badger](https://www.eff.org/privacybadger/faq)) do not let the third party (such as EAP) iiif images / manifests be requested. I think it's a sort of bug on their side (or a too agressive policy), but in any case there should probably be a warning for that.

**Comment by eroux** [comment]
(this is not urgent)

**Comment by eroux** [comment]
@TBRC-pmench I think you were the one reporting this issue, do you still have problems with PrivacyBadger when viewing images of EAP records (such as http://library.bdrc.io/show/bdr:WEAP676-12-2 ) ?

**Comment by TBRC-pmench** [comment]
Yes, this is still a problem but is easily fixed by changing PrivacyBadger settings.

Does not work:
![image](https://user-images.githubusercontent.com/48484924/86370074-3d968600-bc4d-11ea-89cb-d4e02ea2ae04.png)

Works:
![image](https://user-images.githubusercontent.com/48484924/86370147-59019100-bc4d-11ea-94ea-b469c0a855bf.png)

**Comment by eroux** [comment]
oh ok! well that's pretty aggressive but there's not much we can do I suppose... maybe we could try  to detect that and advise users to look at the settings but that could be seen as too intrusive... so closing until a way forward can be found

**Comment by TBRC-pmench** [comment]
I reported it to PrivacyBadger when I first discovered it, but I imagine my one report isn't going to get their attention
