### ISSUE TITLE
understanding results on tbrc.org

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#475]
Hi @xristy here's an interesting mystery I'm puzzled by... it's not really important but if you have time your input would be welcome. If you search "deb ther sngon po" on tbrc.org, you'll find 16 texts, but on BUDA you'll find many more... some of the texts that are not found on tbrc.org are in the outline of W1KG5762, and I don't really understand why tbrc.org doesn't find these (but find others in the same outline)... to be clear, I'm not expecting this to trigger a change on BUDA or tbrc.org, I'm just trying to understand this difference. I know there can be a conservative feeling wrt to the website and that can lead to the impression that BUDA doesn't have the "correct" number of results, because it's different from tbrc.org which is the reference.

**Comment by xristy** [comment]
If I go to W1KG5762 on tbrc and search in the outline I find 20 hits. I have no idea why only one is returned in the db-wide search. On buda the db-wide search produces 20 hits in W1KG5762.

There are 2 hits in W0LULDC322478 on buda and non on tbrc since that Work doesn't exist on tbrc.

Here are some more cases. It's almost like tbrc is returning just 1 hit for each outline, except for the first case below, and the second case below seems an anomaly for buda:

W28960 has 2 hits on tbrc and 1 on buda

W28948 - 1 hit on tbrc and 0 on buda

W7494 - 1 on tbrc and 15 on buda

W3CN22294 - 1 on tbrc and 12 on buda

W4CZ74375 - 0 on tbrc and 1 on buda

W1KG10687 - 1 on tbrc and 2 on buda

W3CN15333 - 0 on tbrc and 1 on buda

**Comment by xristy** [comment]
Indeed in the search query: `/db/modules/gwt/global-search.xqm` in routine `q:outlines-search(...)`:
```
    let $titles0 := collection('/db/tbrc/tbrc-outlines/')//o:node/o:title[ft:query(., $query)]
    let $names0 := collection('/db/tbrc/tbrc-outlines/')//o:node/o:name[ft:query(., $query)]
    let $titles1 := ($titles0, $names0)[ancestor::o:outline/@status = 'released']
                            [not(ancestor::o:outline/o:isOutlineOf/@type = ('taxonomy', 'enumeration'))]
    let $titles2 := q:rem-dups($titles1)
```
The last line of the fragment grabs on the first hit in each Outline. I think our idea was to essentially return an example from the Outline of each Work that had at least one hit, then the user could drill down by visiting the Work and searching within the Outline there.

So it looks like several factors account for the difference between tbrc and buda:

1) tbrc only returns 1 hit for each Outline that has at least one hit
2) tbrc separates results into Works and Texts whereas buda aggregates them, at least to some extent
3) there are objects in buda that not in tbrc
4) there's at least one UI anomaly in tbrc (W28960)

I think this covers it.

**Comment by eroux** [comment]
Ah thanks a lot! I was suspecting something like the "one result per outline" thing... well... I'm not sure users are aware that this happens (at least I think the librarians don't) and that may lead to some misunderstanding, so perhaps let's not bake that feature into BUDA... thanks again!
