### ISSUE TITLE
Capability to create bibliographic citations

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#498]
From a Board member:

One issue I’ve been facing a lot: in the old TBRC website you could easily create a citation for a text that would be formatted (more or less) according to the preferred method. Is there a way to do that in BUDA? It’s an incredibly useful feature, adn I find myself going back to the old website a lot just for that.

**Comment by eroux** [comment]
Thanks! Let's work on that perhaps this week after the per-entity history of the editor. I think the best will be to create a URL like `http://ldspdi.bdrc.io/export/citations/bdr:MW22084/bibframe`... OTOH doing that on the client side would allow us to use mechanisms to have a very direct zotero export, see:

https://www.zotero.org/support/dev/exposing_metadata

This will require a bit of thinking... I'll think of a good architecture and will open different issues (some on the server) that will allow us to handle that

**Comment by eroux** [comment]
@xristy out of curiosity, can you point me to the Java file that handles the export on tbrc.org?

**Comment by eroux** [comment]
So, in this issue we'll describe the user-facing aspect (the buttons, display, etc.). I think one solution could be:
- a button "download citation" in the download menu, with several options (maybe a submenu, maybe a pop-in)
- among these options would be a few different styles, probably the same as those on tbrc.org in a first iteration, see screenshot:

![Capture d’écran de 2021-06-08 13-52-36](https://user-images.githubusercontent.com/60868/121182737-ae81ed00-c863-11eb-9895-01cae677c33e.png)

where:
- Permalink on tbrc.org wouldn't be in the list because we already have it elsewhere on BUDA
- Reference Manager is tied to https://github.com/buda-base/lds-pdi/issues/216 (but could also perhaps be exported like other formats?)
- Generic, Chicago and MLA are citation styles (we could remove / add some, there's a [whole repository](https://github.com/citation-style-language/styles) of such styles)

The mechanism could be that when the user clicks on one of the styles, the javascript:
- fetches the MARCXML ([example](https://purl.bdrc.io/resource/W12827.mrcx))
- uses the MARCXML [zotero translator](https://www.zotero.org/support/dev/translators/coding#web_translators) to convert it into Zotero's internal format
- use [citeproc-js](https://github.com/Juris-M/citeproc-js) to display the data from the previous step into the citation style we want
- display the result in a pop-in

Note that this would only work for `bdr:W[0-9]`, `bdr:MW` and `bdr:IE` ids.

Another caveat is the translation into Tibetan: citeproc-js is [localized](https://github.com/citation-style-language/locales/) in different languages like Chinese and English but not in Tibetan...

Final caveat is the wylie vs. Unicode thing... the MARCXML record has both (linked in a special and unintuitive way), but I'm not sure how it will be transformed into Zotero's internal format... so perhaps the first step needs to be revised at some point... but tbrc.org doesn't seem to convert the citations into Unicode so it's fine for now, no loss of functionality.

Post-final caveat: the MARCXML contains the ALALC transliteration, not the EWTS, so that will be a change from tbrc.org... but for the better I think, let's see!

**Comment by xristy** [comment]
> @xristy out of curiosity, can you point me to the Java file that handles the export on tbrc.org?

Here are the references:

org.tbrc.gwt.common/src/org/tbrc/gwt/common/client/CitationPopup.java

    31: public class CitationPopup extends PopupPanel {
    
org.tbrc.gwt.common/src/org/tbrc/gwt/common/client/DetailNavigationPanel.java

    188: protected HTML makeCitation(String rid, String type, String nm) { 

org.tbrc.gwt.common/src/org/tbrc/gwt/common/server/Citation.java


Used in

    org.tbrc.gwt.outline/src/org/tbrc/gwt/outline/client/TreeView.java

**Comment by eroux** [comment]
excellent, thanks!

**Comment by eroux** [comment]
Note that the method to start from MARCXML unfortunately doesn't work for outline nodes... so we need to start from another export in ldspdi

**Comment by eroux** [comment]
We can create bibliographic citations in different styles... here's the (intimidating) list of possibilities: https://www.zotero.org/styles/ . I think `chicago-fullnote-bibliography` is a reasonable choice... we can support a few others. @JannTibetan what are the ones you think are the most used in the field?

**Comment by JannTibetan** [comment]
Let me ask around for a list of the too 3 citations styles.

**Comment by eroux** [comment]
@JannTibetan did you get some answers?

@berger-n I've finally finished a first iteration of the server-side thing, and also created [an example](https://github.com/eroux/citation-experiments-js) of how to use it in the browser. Here are a few pointers:
- look at the console when you open the demo.html file in your browser (on your local file system), it prints the html to be displayed
- http://ldspdi-dev.bdrc.io/CSLObj/bdr:MW22084 is an example of the server-side thing, it creates 4 outputs (English, Transliterated, Chinese and Tibetan), which I think could all be displayed in a first iteration (or perhaps according to the UI language, where the Transliterated would be displayed for all the UI languages)
- the display should be in a popin
- for some reason the `zh_CN` locale doesn't work in my demo, which is annoying... I'll continue to debug that but we can use the `en_US` one in the meantime
- the xml files could be hardcoded somewhere in the javascript like I did for the demo, or be in the static files and be fetched (I think the latter would be best)
- the citation style could be a selector at the top of the popin

**Comment by eroux** [comment]
just for reference, the issue about `zh_CN`: https://github.com/larsgw/citation.js/issues/216

**Comment by eroux** [comment]
ok, there's a workaround for the `zh_CN` issue, the demo [has been fixed](https://github.com/eroux/citation-experiments-js/commit/0d08100f5db491aaf19ac33c4daf297c54759609) and is now fully working! Just as a note, we should add the Tibetan locale for citations at some point but this is quite a lot of development and it won't happen any time soon

**Comment by berger-n** [comment]
first shot at the UI:

![Kazam_screencast_00034 mp4](https://user-images.githubusercontent.com/33383857/124157540-2b863800-da99-11eb-94e2-e1165ee76844.gif)

(deployed here http://library-dev.bdrc.io/show/bdr:W22084
though for an unknown reason citation popup won't show up...)

**Comment by berger-n** [comment]
> (deployed here http://library-dev.bdrc.io/show/bdr:W22084
though for an unknown reason citation popup won't show up...)

fixed

**Comment by eroux** [comment]
Ah this is good, thanks!! Here's a proposal:
- let's have an icon for the download button (something like [that](https://www.iconfinder.com/icons/2561424/download_icon), perhaps in a circle)
- let's have another button "cite this item", with an icon (like the one on [hollis](https://hollis.harvard.edu/primo-explore/search?query=any,contains,bodhisattva&tab=everything&search_scope=everything&vid=HVD2&facet=tlevel,include,available_onsite&lang=en_US&offset=0))

perhaps it would be advantageous to have just one button that opens a popup instead of the menus à la download button, that would make the integration in outlines easier... although we could also have a download button in the outlines directly so we could have the menu in both... 

example of possible popup with everything (so avoiding the need for menus): 
- https://www.jstor.org/stable/24655521 
- https://hollis.harvard.edu/primo-explore/search?query=any,contains,bodhisattva&tab=everything&search_scope=everything&vid=HVD2&facet=tlevel,include,available_onsite&lang=en_US&offset=0

I like the "copy to clipboard" button of hollis... also, perhaps in the popup we will have the "export to MARC" and "export to RIS" buttons (instead of in the download menu)

**Comment by berger-n** [comment]
updated UI with icons and popup content à la Hollis: http://library-dev.bdrc.io/show/bdr:W22084

![Kazam_screencast_00038 mp4](https://user-images.githubusercontent.com/33383857/124280001-73b06380-db48-11eb-8dbe-96c9567cbdf3.gif)

not sure what to do with MARC/MARCXML/RIS exports though, maybe an "Export" button next to "Copy" in popup (styled like "Download" but with [this kind of icon](https://www.flaticon.com/free-icon/export_154838)) opening a choice like citation language selector?

**Comment by eroux** [comment]
perfect! I think the pop up could be centered but other than that the UX is good! Yes, the two buttons would be perfect (perhaps more will be added in the future)

**Comment by berger-n** [comment]
ok! so UI seems ready now: https://library-dev.bdrc.io/show/bdr:MW22084

![image](https://user-images.githubusercontent.com/33383857/124301828-a6665600-db60-11eb-8b13-7f4eb04e850d.png)

(label for RIS export taken from #511)

**Comment by eroux** [comment]
Looks perfect thanks!

**Comment by eroux** [comment]
For the styles, let's use in this order:
- [MLA](https://github.com/citation-style-language/styles/blob/6152ccea8b7d7a472910d36524d1bf3557a83bfc/modern-language-association.csl)
- [Chicago](https://github.com/citation-style-language/styles/blob/6152ccea8b7d7a472910d36524d1bf3557a83bfc/chicago-fullnote-bibliography.csl)
- [APA](https://github.com/citation-style-language/styles/blob/6152ccea8b7d7a472910d36524d1bf3557a83bfc/apa.csl)

**Comment by berger-n** [comment]
almost ready to work (at least locally):

![Kazam_screencast_00043 mp4](https://user-images.githubusercontent.com/33383857/124601242-e763b080-de67-11eb-8a8c-d439824f22b3.gif)

---

- all `title` are `null` in data though: http://purl.bdrc.io/CSLObj/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/124600293-d9f9f680-de66-11eb-92c2-4450cd1c663a.png)
---

- `citation-js` crashes the app on startup when using build version...
  loaded from CDN app starts, yet error is still there and prevents citations from working: http://library-dev.bdrc.io/show/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/124600603-2c3b1780-de67-11eb-9da3-c021c37ed84b.png)

**Comment by eroux** [comment]
ah excellent, thanks a lot! Can you report the issue with the crash on https://github.com/citation-js/citation-js ? the dev is quite reactive. You're right about the null title, the MW version has it on http://purl.bdrc.io/CSLObj/bdr:MW22084 but yes, I'll fix the W

**Comment by berger-n** [comment]
ok thanks, good to know! 
opened an issue here: https://github.com/citation-js/citation-js/issues/128
for now let me show a gif with everything working fine :smile::

![Kazam_screencast_00044 mp4](https://user-images.githubusercontent.com/33383857/124612627-c6ed2380-de72-11eb-968c-668fa03a0c0a.gif)

**Comment by eroux** [comment]
http://purl.bdrc.io/CSLObj/bdr:W22084 is now fixed

**Comment by berger-n** [comment]
issue with `citation-js` is now fixed: http://library-dev.bdrc.io/show/bdr:MW12827

![image](https://user-images.githubusercontent.com/33383857/124639789-daa58380-de8c-11eb-9911-646b46c1d88b.png)

**Comment by eroux** [comment]
Fantastic, this is great!! Perhaps just in terms of css we could highlight the citation a bit, perhaps in a box, or on a different background, à la hollis:

![Capture d’écran de 2021-07-06 19-26-22](https://user-images.githubusercontent.com/60868/124642503-33c2e680-de90-11eb-8b12-b1112b8e9242.png)

**Comment by berger-n** [comment]
updated css, is it ok like this? http://library-dev.bdrc.io/show/bdr:W12827

![image](https://user-images.githubusercontent.com/33383857/124735207-1fc1c800-df16-11eb-9b3e-d539a7284ad9.png)

**Comment by eroux** [comment]
Looks good to me! @JannTibetan what do you think? Let's add the BDRC ID and the URL in the citation, I'll experiment to find the best way to do that

**Comment by eroux** [comment]
useful links:
- https://style.mla.org/citing-work-in-digital-archives/

**Comment by berger-n** [comment]
@eroux is it something you want to change in the `/CSLObj/` API or to be done afterwards in the client?

**Comment by eroux** [comment]
I'm not sure yet, it's just some notes for now, I'll have a closer look tomorrow

**Comment by berger-n** [comment]
ok thanks!

**Comment by eroux** [comment]
so, these are adjustments to make in the styles, because they're small discrepancies with the specifications... but since we have our own files, I'll patch them directly. Also, FYI: https://github.com/citation-style-language/styles/issues/5545 (this might require a little hack in the code)

**Comment by eroux** [comment]
ok, so:
- for MLA, we'll have to patch the URL manually (removing `http://` and `https://` at the beginning) before we pass it on to the function that creates the citation
- MLA style is fine, here are new APA and Chicago styles that suit our purposes better, I named them `apa-bdrc` and `chicago-fullnote-bibliography-bdrc` so that they're not confused with the others:
   * http://eroux.fr/apa-bdrc.csl
   * http://eroux.fr/chicago-fullnote-bibliography-bdrc.csl

Then we might want to add `[BDRC bdr:W123]` as a suffix to the citation, but there's an easy way to do so in citation-js, I'll make some experiments

**Comment by eroux** [comment]
so, we can append the thing by calling

```
        var res = cite.format('bibliography', {
          format: 'html',
          template: 'apa-bdrc',
          lang: "en-US",
          append: ({id}) => {
            return ` [BDRC ${id}]`
          }
        })
```

(to be adjusted)

**Comment by eroux** [comment]
URL line breaking rules in Chicago:

![Capture d’écran de 2021-07-08 10-39-19](https://user-images.githubusercontent.com/60868/124891090-f1f18780-dfd8-11eb-8228-8cd007a87b86.png)

**Comment by berger-n** [comment]
ok for the url, branch is now merged and deployed in prod: https://library.bdrc.io/show/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/124895912-4434a780-dfdd-11eb-8df3-96a4dff1902a.png)

**Comment by eroux** [comment]
fantastic! I think the citation is perfect now, @JannTibetan what do you think? Two CSS things:
- let's make the text breathe a bit more by adding more padding in the text area, or perhaps thinner (no shadow) border?
- let's make the box stick to the "cite this item" anchor when scrolling

**Comment by berger-n** [comment]
box know sticks to the anchor when scrolling
regarding text area, I added some space and removed shadow border: https://library.bdrc.io/show/bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/124906806-c1651a00-dfe7-11eb-82fe-6d0bc8029807.png)

(text is supposed to be aligned on the left as it used to but after build it's a bit off, working on it)

**Comment by eroux** [comment]
perfect, thanks!

**Comment by eroux** [comment]
ah wait, when you change the language it closes the whole popup

**Comment by berger-n** [comment]
thanks! that's all fixed now: https://library.bdrc.io/show/bdr:MW22084?tabs=bdr:W22084

![image](https://user-images.githubusercontent.com/33383857/124914037-24f34580-dff0-11eb-9d29-1790a5563aed.png)

**Comment by berger-n** [comment]
wait... is it on purpose that *Buddhist Digital Resource Center* is displayed in MLA style but not in APA/Chicago?

![image](https://user-images.githubusercontent.com/33383857/124915185-8a940180-dff1-11eb-8d69-4686d829b715.png)

![image](https://user-images.githubusercontent.com/33383857/124915105-75b76e00-dff1-11eb-8641-d535cb1bb653.png)

![image](https://user-images.githubusercontent.com/33383857/124915138-7fd96c80-dff1-11eb-95ea-e728f68b0116.png)

**Comment by eroux** [comment]
yes, that's normal, no problem!

**Comment by eroux** [comment]
Oh, I almost forgot! Let's also add this to the outlines (the API, results, UI, etc. are exactly the same)

**Comment by berger-n** [comment]
not sure what you mean as it is already there: https://library.bdrc.io/show/bdr:MW12827_A79904
is it about adding the Citation icon near the image, "i", link, etc. here?

![image](https://user-images.githubusercontent.com/33383857/124917541-40f8e600-dff4-11eb-9a7a-f57b8bc7591b.png)

**Comment by eroux** [comment]
that's what I mean yes

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:MW12827?part=bdr:MW12827_A79904

![image](https://user-images.githubusercontent.com/33383857/124935638-1dd73200-e006-11eb-9d71-7b830ddc1a8c.png)

BTW is it supposed to work in Etext outlines as well? 
seems not to: http://purl.bdrc.io/CSLObj/bdr:VLIE0OPP010556_v003

**Comment by eroux** [comment]
Excellent, thanks!! Yes, etexts are not ready for that yet... closing, excellent job!

**Comment by JannTibetan** [comment]
From a board member:

Hi, Jann. This is brilliant!  And it includes export to MARC.... that's a huge help for librarians.

If others agree, I would suggest fine-tuning it to capitalize only the first letter of any title.
It is the most likely form to be used. The user can capitalize proper names etc  if needed.

Also, just now I wanted to see how your "diacritic-letters" -- e.g. the "m" in Kam tshang -- are rendered.  But, in this instance, the "article" title was not caught by the citation.  Just the Collected Works title.  Does that need investigating?

**Comment by eroux** [comment]
The titles and names that appear in the different languages are different. Perhaps you would prefer the "transliterated" to be the default? (it seems to fit your expectations better)

**Comment by eroux** [comment]
(also, I'm not sure what diacritic letter you're talking about?)

**Comment by eroux** [comment]
the casing is actually not easy to change unfortunately... it's feasible though, I'll patch the CSL and the style files

**Comment by eroux** [comment]
so, now that https://github.com/buda-base/lds-pdi/issues/218 is done, the last touch is to change the default language to Transliterated when the UI is set to English. @berger-n can you look at it when you come back?

**Comment by berger-n** [comment]
language is now set to `latn` if no selection has been made when locale is English: http://library-dev.bdrc.io/show/bdr:MW2KG207344

![image](https://user-images.githubusercontent.com/33383857/126145326-ac0e92ba-2ed0-4334-bb44-06041da6707b.png)

**Comment by eroux** [comment]
perfect, thanks!
