### ISSUE TITLE
Pages not loading on BUDA

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/public-digital-library#512]
@eroux @xristy images currently not loading on BUDA:

![not-loading](https://user-images.githubusercontent.com/19354126/124362944-54780b80-dc06-11eb-8aec-0ee4bf6e3e4e.gif)

<img width="1288" alt="Screen Shot 2021-07-03 at 1 53 52 PM" src="https://user-images.githubusercontent.com/19354126/124362956-5f32a080-dc06-11eb-8a85-92209c587396.png">

<img width="1662" alt="Screen Shot 2021-07-03 at 1 59 27 PM" src="https://user-images.githubusercontent.com/19354126/124363042-eaac3180-dc06-11eb-9f72-3bccf664aa6f.png">

**Comment by eroux** [comment]
thanks! there was no room left on the hard drive of the server... @xristy the problem comes from Fuseki that's growing out of control... I've removed the test database so that there's room until Monday. But the weird thing is that the auth database is around 50GB, which is weird as it contains almost nothing... perhaps we should investigate that?

**Comment by xristy** [comment]
@eroux databases core is fine - i.e., it has grown 10-15GB over the past 6 months or so which is reasonable.

The issue is the auth db, which I actually know nothing about. I know it was set up by @MarcAgate but I don't know what's supposed to be in there and such. I thought is was some sort of auxiliary db of user profile data which shouldn't be more than a few MB I would think. I doubt there's more than at most a few hundred registered users based on current usage stats.

I removed the lucene-test index for an additional 5.82 GB.

**Comment by xristy** [comment]
further `/usr/local/share/.cache/yarn` is consuming 23.874 GB
```
admin@buda1:/usr/local/share/.cache/yarn$ sudo du -sm *
14116	v2
9759	v6
```
This may be related iiif somehow?

**Comment by eroux** [comment]
Auth is the private data of users, there should be almost nothing there... I'll analyze that on Monday...

Good finding for the yarn cache! It's just the cache for the deployment of  javascript apps, there's really no reason for it to grow out of hands like this!

**Comment by eroux** [comment]
(related: https://github.com/buda-base/buda-base/issues/40 )

**Comment by eroux** [comment]
well, here's the weird thing: the auth dataset only has 22244 triples, in 1256 graphs... so 50GB looks quite excessive (there's no plain text thing, it's just names and email addresses). Perhaps this is an instance of TDB1 growing out or control because the same data is written many times? @xristy perhaps we could create a script that:
- stops fuseki
- dumps data from auth (with the tdb tools)
- removes the directory
- start fuseki again
- restores the dump

?

**Comment by eroux** [comment]
@xristy do you think you could look at such a script? If not that's fine, I'm happy to do it! (the auth db is still growing a lot)
