### ISSUE TITLE
updating the number of works in a topic fails

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#548]
I suspect it's because of withdrawn works? see on https://library.bdrc.io/search?t=Work&r=bdr:P252&pg=1&f=tree,inc,bdr:T208 :

![topicfacetissues](https://user-images.githubusercontent.com/60868/131553430-5fdfc4a6-3336-4cc0-94b1-69c502930768.png)

**Comment by berger-n** [comment]
indeed there are 5 more non released items:

![Screenshot_20210901_085032](https://user-images.githubusercontent.com/33383857/131625263-eb63c93f-5a04-416f-a2c4-8b9babaec10f.png)

this needs a fix

**Comment by eroux** [comment]
yes, thanks!

**Comment by berger-n** [comment]
what I have now locally:

![Screenshot_20210901_102749](https://user-images.githubusercontent.com/33383857/131638537-920818b4-8c9f-4f74-bf06-efd75292c0fb.png)

better than formerly:

![Screenshot_20210901_102842](https://user-images.githubusercontent.com/33383857/131638686-7d1dd011-a764-497b-8491-88d413030d25.png)

however it's not clear yet how to fix the 8 in "3 / 8" because it comes from the tree in the query itself...
let's give it a try

**Comment by eroux** [comment]
better indeed! perhaps the tree shouldn't count the non-released works... I think it would make sense

**Comment by eroux** [comment]
(see https://github.com/buda-base/lds-pdi/issues/221 )

**Comment by eroux** [comment]
that works now! thanks!

**Comment by berger-n** [comment]
thanks! 
deployed: https://library.bdrc.io/search?t=Work&r=bdr:P252&pg=1&f=tree,inc,bdr:T208

![Screenshot_20210901_115325](https://user-images.githubusercontent.com/33383857/131651257-29728c4a-8b3a-49fa-a51e-0af427c46df2.png)

**Comment by berger-n** [comment]
thanks! 
deployed: https://library.bdrc.io/search?t=Work&r=bdr:P252&pg=1&f=tree,inc,bdr:T208

![Screenshot_20210901_115325](https://user-images.githubusercontent.com/33383857/131651257-29728c4a-8b3a-49fa-a51e-0af427c46df2.png)
