### ISSUE TITLE
improvements of the "preview" button in works results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#549]
when in the work search results and clicking on "preview", 3 instances are previewed, but without a strong indication of others are available. There should be a little something at the bottom saying something like "X more are available, browse all"

**Comment by eroux** [comment]
actually, I think we could improve it further by:
- in the case where there are more than 3 instances, rename "preview" into "preview 3"
- in the case where there are 3 instances or less, remove "preview" and "see all" with "see instances" that would do the same thing as "preview" (no need to go to the full list when there are only 2 or 3...)

**Comment by eroux** [comment]
and also rename "see all" into "see all X" where X is the number of instances

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Work

![Screenshot_20210903_122623](https://user-images.githubusercontent.com/33383857/131991044-7fe154aa-07c0-4e47-9120-c61116566bc4.png)
---
![Screenshot_20210903_122644](https://user-images.githubusercontent.com/33383857/131991078-b8aeda9c-9470-44df-a40f-9ab688aa2dc0.png)
---
![Screenshot_20210903_122739](https://user-images.githubusercontent.com/33383857/131991179-460c0296-63ff-4243-8f19-fa888a4f6887.png)
---
![Screenshot_20210903_122845](https://user-images.githubusercontent.com/33383857/131991304-623641c6-ad6e-46b6-b956-a81f2e953b43.png)

now there might be an issue with number of versions given because it's often not accurate
see latter screenshot (said to have 2 but 1 returned
it also happens that 4 or more results are expected but only 2 are returned so the "see more button" can be disappointing...

**Comment by eroux** [comment]
Perfect, thanks! Perhaps in the message "X more available, browse all" the link should only be on the "browse all", and also I think we should have the little icon that shows it's a link at the end? Once it's done, let's deploy!

**Comment by eroux** [comment]
I fixed the issue of the number of associated versions, thanks for pointing it out!

**Comment by berger-n** [comment]
done, should look like this:

![Screenshot_20210903_150649](https://user-images.githubusercontent.com/33383857/132009951-85e64024-d99d-40bb-bc6d-d8118c8417a4.png)

but there seems to be something wrong with number of associated versions
it's always equal to 2 even for [first result](https://library.bdrc.io/search?r=bdr:WA0RT3216&t=Instance) ([bdr:WA0RT3216](https://library.bdrc.io/show/bdr:WA0RT3216))
BTW is it on purpose that associated instances query returns both Version and corresponding Scan?

regarding the link icon, I'm not sure because everywhere else it's associated with a resource on an external site
should I give it a try nonetheless?

**Comment by eroux** [comment]
ah right, the icon shouldn't be there, sorry...

thanks for the pointers. I fixed the issue with https://library.bdrc.io/search?r=bdr:WA0RT3216&t=Instance&s=title%20forced I'll continue investigating the issue with the number of versions... It's not particularly obvious, this part of the query is quite complex...

**Comment by eroux** [comment]
ok, I fixed it, I think we're good! thanks!

**Comment by berger-n** [comment]
well done, thanks! it's perfect
deployed: https://library.bdrc.io/search?q=%22spyod%20%27jug%22~1&lg=bo-x-ewts&t=Work
