### ISSUE TITLE
withdrawn records displayed in search results

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#555]
see https://library.bdrc.io/search?q=%22lokesh%20chandra%22&lg=en&t=Person&n=2 for instance. Is there some flaw in the [query](https://purl.bdrc.io/lib/personGraph?LG_NAME=en&L_NAME=%22lokesh%20chandra%22)?

**Comment by eroux** [comment]
nevermind, it's some silliness in the data...

**Comment by berger-n** [comment]
this is because P6225 is `sameAs` for some records in [query](https://purl.bdrc.io/lib/personGraph?LG_NAME=en&L_NAME=%22lokesh%20chandra%22) 

![Screenshot_20210909_135331](https://user-images.githubusercontent.com/33383857/132681081-4d731dcb-adb3-494f-8d39-7e1625a07558.png)

default mechanism is to replace external record by `sameAs` from BDRC if any
but I think we can easily add "not withdrawn" condition  to this
do you want me to try?

**Comment by eroux** [comment]
I think it's fine, the issue is that TOL shouldn't reference this ID, I'll discuss the possibility of a new import that would fix a number of issues
