### ISSUE TITLE
improving message when search gives no result

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#620]
Here's a message designed by @TBRC-TimB and @JannTibetan :

```
There are no results matching your search: {search string}

BDRC contains thousands of texts, you may want to try modifying your search to get the best results. 
 - Try an alternate title for the work you are looking for, as we do not have all variant titles in our metadata {an example would be nice here}
 - Search on a shorter string of syllables, try to limit your search to 5-7 significant syllables {example}
 - Double check your search for typos

As a last resort, you can try searching for the author of the text you are searching for, and connecting to that work through their Related Works.
```

I'm not sure it's really easy to automatically propose something relevant as `{example}` though...

**Comment by JannTibetan** [comment]
I'm sorry I never responded to this. I'll edit the text over the weekend.

**Comment by JannTibetan** [comment]
There are no results matching your search: {search string}

BDRC contains thousands of texts, you may want to try modifying your search to get the best results. 
- Search on a shorter string of syllables, preferably the core part of the title {lam rim chung ngu'i zin bris instead of lam rim chung ngu'i zin bris blo gsal rgya mtsho'i 'jug ngogs}
- Double check your search for typos

**Comment by JannTibetan** [comment]
BDRC contains thousands of **person records**, you may want to try modifying your search to get the best results.
•	Search on a shorter string of syllables by eliminating titles, geographical names, and so on  {'jam dbyangs nor bu instead of co ne sa skyong 'jam dbyangs nor bu}
•	Double check your search for typos

**Comment by JannTibetan** [comment]
The place and topic ontologies are quite unsystematic so it would be very difficult to give helpful advice on them. For instance, this weekend I discovered that ཞང་ཞུང་ is not a topic in the ontology.

**Comment by berger-n** [comment]
done: 
- Persons: http://library-dev.bdrc.io/search?q=%22drimedodzer%22~1&lg=bo-x-ewts&t=Person&s=closest%20matches%20forced
  
  ![image](https://user-images.githubusercontent.com/33383857/151845740-c3759b70-a5ec-4783-97b9-ad0814a36502.png)


---

- Works/Versions: http://library-dev.bdrc.io/search?q=%22drimedodzer%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced
  
  ![image](https://user-images.githubusercontent.com/33383857/151845888-6fac465e-c0d1-4393-9eea-51719d5e7b26.png)

**Comment by JannTibetan** [comment]
Thanks @berger-n  It works well!
Just one small correction. The works/version message has a typo: lam rim chung ngu'i zin bris**w**  The w at the end should be deleted.

**Comment by berger-n** [comment]
ok thanks! fixed typo and deployed: https://library.bdrc.io/search?q=%22drimedodzer%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly&s=closest%20matches%20forced

![image](https://user-images.githubusercontent.com/33383857/151950151-2283cb72-9f86-4429-be44-b6e8047b842d.png)

**Comment by JannTibetan** [comment]
It works well, thanks
<img width="916" alt="Screen Shot 2022-02-01 at 8 31 55 AM" src="https://user-images.githubusercontent.com/44705185/151977715-8ffd1a27-9375-498c-8c43-21b7903df1c1.png">
!
