### ISSUE TITLE
use case for an "expand all" button in etext search

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#659]
Here's a use case from a user who works on Mongolian fragments of canonical texts:
- the fragment contains only segments of sentences (because it's physically damaged)
- the researcher looks at part of a sentence, translates it into Tibetan, and searches on the website, which gives a lot of matches (even when they restrict to the Canon)
- the researcher then looks at the next (non-contiguous) part of sentence and translates it into Tibetan too, then searches the result in a browser search while the results of the first search are displayed

This works ok on tbrc.org, but less well on BUDA because the extracts are shorter and the researcher needs to expand everything first, then do a browser search.

Now, ideally, the workflow would be simplified through the use of the "AND" keyword (which she will test), but perhaps a "expand all" button would be relevant. This might be quite a performance hit though... perhaps we can be creative about this use case!

**Comment by JannTibetan** [comment]
Can you give an example of this on tbrc.org. I'm having trouble visualizing it. Thanks

**Comment by eroux** [comment]
sure, compare the results of https://library.bdrc.io/search?q=%22rang%20bzhin%20mkhyen%20nas%20de%20dang%20mthun%20pa%22~1&lg=bo-x-ewts&t=Etext :

![Capture d’écran de 2022-02-02 14-40-17](https://user-images.githubusercontent.com/60868/152164936-e8344823-0283-42e6-ab75-b5f95fe9046f.png)

and on the old website:

![Capture d’écran de 2022-02-02 14-39-52](https://user-images.githubusercontent.com/60868/152164971-f39840b8-7c02-442c-b946-44f0f54e54c3.png)

on which the excerpts are longer, so you can do a browser search (ctrl F) for something else, while they are shorter on BUDA

**Comment by JannTibetan** [comment]
Ah ok, yes I see her point. In the short term can we increase the amount of etext that appears in the search results?

**Comment by berger-n** [comment]
> Ah ok, yes I see her point. In the short term can we increase the amount of etext that appears in the search results?

something straightforward to do is indeed to display full data received by query (instead of using "(...)" to shrink it): http://library-dev.bdrc.io/search?q=%22rang%20bzhin%20mkhyen%20nas%20de%20dang%20mthun%20pa%22~1&lg=bo-x-ewts&t=Etext

![Screenshot_20220202_153917](https://user-images.githubusercontent.com/33383857/152175094-3a6d5118-5600-440e-9f1b-0fd068ba6555.png)

in this example I've also set *Other Matches* to be displayed by default
I think a button to toggle between normal and this mode would be best
something like *Expanded view*, maybe at the top of results? next to *Sort by* widget

![image](https://user-images.githubusercontent.com/33383857/152174955-f67d511d-aa8c-49de-872d-e53da9bfe323.png)
---

I don't know what's possible regarding query though (increase size of returned matching text on demand?)
expanding all results at once seems not to be an option as it requires lots of data both to load and display at once
@eroux wdyt?

**Comment by eroux** [comment]
yes I think a button that does what you say would be best. Or actually perhaps at least showing the whole excerpt by default would be good... Showing the other matches probably not, let's keep it behind a "show all matches" button

There would be a performance hit to change the query but it may not be that bad (at least if there aren't too many results, which is difficult to anticipate). What we might want to do in that case is to have a parameter to the query to switch the mode, and perhaps only activate this parameter when the user clicks on the button... but that's more complex and we can keep it for later. Let's implement that and I'll ask the researcher if she's happy with the result

**Comment by berger-n** [comment]
now with a button for other matches: http://library-dev.bdrc.io/search?q=%22rang%20bzhin%20mkhyen%20nas%20de%20dang%20mthun%20pa%22~1&lg=bo-x-ewts&t=Etext

![Kazam_screencast_00071 mp4](https://user-images.githubusercontent.com/33383857/152205661-cf9cc3b7-8a40-444a-a479-0184a8e53c28.gif)

**Comment by eroux** [comment]
I think this is very good, thanks a lot!

**Comment by JannTibetan** [comment]
Looks wonderful, thanks! So now the search results provide a sufficient amount of context (for advanced language study and the Russian woman's research) and the "expanded context" button gives you enough text so that a good reader can use it to figure out the rhetorical context of the search string. Makes me think of this model:
![IMG_2905](https://user-images.githubusercontent.com/44705185/152227600-6d980f70-28ef-46e3-9df6-4e600f93ab42.jpeg)

**Comment by eroux** [comment]
@berger-n I can't see it anymore on library-dev, but I think it's good, let's deploy!

**Comment by berger-n** [comment]
merged branch and deployed: https://library.bdrc.io/search?q=%22rang%20bzhin%20mkhyen%20nas%20de%20dang%20mthun%20pa%22~1&lg=bo-x-ewts&t=Etext

**Comment by eroux** [comment]
perfect, thanks! I think this will be a great help to many users. I've informed the person who made the request

**Comment by eroux** [comment]
the user is very happy, thanks!
