### ISSUE TITLE
Improving Outline search performance?

### ISSUE THREAD

**Issue by TBRC-pmench** [buda-base/public-digital-library#663]
With the caveat that this could be my local machine, I experienced a significant lag when typing in a search in the Outline search bar. You can see what I mean in this screen recording:

https://user-images.githubusercontent.com/48484924/152399201-7f033332-ed20-49e2-9fe2-b820568e6f55.mp4

I typed _thugs rje chen po'i dmar khrid phyag rdzogs zung 'jug gi don 'dus go bder bkod pa rgan mo mdzub tshugs_ but it was difficult to tell whether it was working or had frozen because the letters wouldn't appear on the screen as I typed (this also makes it difficult for users to tell if they've made a typo). As you can see, I eventually just clicked to search despite the fact that the full title that I had typed had yet to appear in the search bar.

This was on Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**Comment by eroux** [comment]
the version is https://library.bdrc.io/show/bdr:MW1KG8321 (right @TBRC-pmench ?) but I can't reproduce it... can you @berger-n ?

**Comment by berger-n** [comment]
thanks a lot @TBRC-pmench for the feedback!
and yes @eroux I can reproduce at least partially (maybe it depends on how fast your machine is)
anyways I've optimized search bar so that now typing keyword won't trigger whole page rendering
you can test it here: http://library-dev.bdrc.io/show/bdr:MW1KG8321

![Kazam_screencast_00077 mp4](https://user-images.githubusercontent.com/33383857/152534923-41ec13ca-273d-4fbf-9912-16a3e5a1c6d2.gif)

**Comment by TBRC-pmench** [comment]
Much improved! Thank you, it works perfectly now.
