### ISSUE TITLE
link to the specific page on IA

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#684]
For outline nodes, it would be useful to have the link to IA point to the specific volume / page

**Comment by berger-n** [comment]
could you provide an example? 
not sure where to go from here

- looking at https://library.bdrc.io/show/bdr:MW1PD95844#outline, link to specific pages in IA are of the form [https://archive.org/details/bdrc-W1PD95844/ **bdrc-W1PD95844-100** /page/n11/mode/2up](https://archive.org/details/bdrc-W1PD95844/bdrc-W1PD95844-100/page/n11/mode/2up)
where there is a additional "item id" bdrc-W1PD95844-100 added by IA on the fly 
  in another example, link is [https://archive.org/details/bdrc-W3CN3408/ **bdrc-W3CN3408-10** /page/n11/mode/2up](https://archive.org/details/bdrc-W3CN3408/bdrc-W3CN3408-10/page/n11/mode/2up)
  in a third one, https://archive.org/details/bdrc-W20510 (scans older that some date I guess?) there's no specific link to a page because it's not viewable in IA

- from what I see page number is local to a volume like https://library.bdrc.io/show/bdr:I1PD95847
  but there are no such volumes on Internet Archive https://archive.org/details/bdrc-I1PD95846: `Item cannot be found`

**Comment by eroux** [comment]
ok, so if I understand correctly, the algorithm for volumes goes as follows:

- https://archive.org/details/bdrc-W1PD95844/bdrc-W1PD95844/ is volume 1
- https://archive.org/details/bdrc-W1PD95844/bdrc-W1PD95844-1/ is volume 2
- https://archive.org/details/bdrc-W1PD95844/bdrc-W1PD95844-n/ is volume n+1

so I think this could be all determined in the contentLocation, with the contentLocationInstance (giving W1PD95844), the volume number and the first image. does that work?

**Comment by berger-n** [comment]
should work
thanks!

**Comment by berger-n** [comment]
now on node page as well: http://library-dev.bdrc.io/show/bdr:MW1PD95844_3386

![image](https://user-images.githubusercontent.com/33383857/170091845-03a60b60-1efe-4502-94bc-954444f2eed0.png)

**Comment by berger-n** [comment]
thanks! done: 
- http://library-dev.bdrc.io/show/bdr:MW1PD95844
  
![image](https://user-images.githubusercontent.com/33383857/170216762-9bc20df0-3ca4-40b4-8d0d-ff4658b620e2.png)

---

- http://library-dev.bdrc.io/show/bdr:MW12827
  
![image](https://user-images.githubusercontent.com/33383857/170216885-67297f77-1bd6-4956-9ca0-de2df891f7e1.png)

**Comment by eroux** [comment]
that looks perfect, thanks! let's deploy

**Comment by berger-n** [comment]
deployed: https://library.bdrc.io/show/bdr:MW1PD95844
