### ISSUE TITLE
language display in mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#750]
in Mirador, there are some important places where the UI language should be used (as opposed to the data language), for instance on

https://library.bdrc.io/show/bdr:W4CZ321174?uilang=en#open-viewer

it should be used here:

![Capture d’écran de 2022-08-31 17-40-50](https://user-images.githubusercontent.com/60868/187721153-b458b793-4934-4224-955b-847bb409778d.png)

![Capture d’écran de 2022-08-31 17-41-01](https://user-images.githubusercontent.com/60868/187721195-5c8999f3-21e9-4f1d-b3bb-9c97b3342c2b.png)

**Comment by eroux** [comment]
https://github.com/buda-base/public-digital-library/issues/638 is a duplicate

**Comment by berger-n** [comment]
done: https://library.bdrc.io/show/bdr:W4CZ321174#open-viewer
- data in Tibetan, UI in English:

 ![image](https://user-images.githubusercontent.com/33383857/187947286-2433e92e-c89b-48cc-8854-f30597fad3ca.png)

 ![image](https://user-images.githubusercontent.com/33383857/187947364-4c78ff3b-f7ac-4ae8-8923-4dabcbedde68.png)

---

- data in Wylie, UI in Tibetan:
 
 ![image](https://user-images.githubusercontent.com/33383857/187947635-67ae665c-0348-484f-9eb5-d399c506e086.png)

 ![image](https://user-images.githubusercontent.com/33383857/187947938-aef1a423-8332-44bc-b645-b64ebaafca5d.png)

---

note that "Images" in Tibetan is a copy-paste of mine in order to check if it was working

regarding Chinese (and Khmer if needed) I'll dig into https://github.com/buda-base/public-digital-library/issues/637

**Comment by eroux** [comment]
perfect, thanks a lot! this is a very noticeable improvement!
