### ISSUE TITLE
minor improvements in outlines display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#784]
We need to improve https://library.bdrc.io/show/bdr:MW1NLM22 a little bit:
- when there's no content location (like in our case), we should just consider that the text is in volume 1 and print the warning that we display when we have volume information but not image location information (https://github.com/buda-base/public-digital-library/issues/648)
- we should add `incipit` to the list of properties that are displayed by default
- when there's no information displayed without clicking on "see more" (as is the case in many nodes here), we should just act as if the user had clicked on "see more"

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/show/bdr:MW1NLM22

![image](https://user-images.githubusercontent.com/33383857/203339042-abe63525-d1c9-4efa-8e95-fbf712c60d4d.png)
---

- [x] `incipit` is now always displayed (tested it before completing next point)
- [x] show hidden properties when no visible ones
- [x] add link to viewer with warning 
---

a few remarks regarding node records: https://library-dev.bdrc.io/show/bdr:MW1NLM22_O1NLM22_004
- there's no link to images
- there's a `bdo:title` property and not `bdo:hasTitle` (should I add it to main properties to put it back to top or is it a typo)
- note that in current outline case this record is skipped when closing viewer (because we're actually on the scans record)
  should closing the viewer make user go back to this node record as it does for other outlines? [example](http://library-dev.bdrc.io/show/bdr:MW12827_80B05B?s=%2Fshow%2Fbdr%3AMW12827#open-viewer)

**Comment by eroux** [comment]
oh thanks! I was wondering why the title wasn't displayed, that's a typo indeed, thanks for spotting it!

I'm not sure what you mean by "there's no link to images"?

(Also, I'm thinking perhaps when there's a warning there could be an alert with the message, to make sure the user got it?)

Oh I see what you mean about the behavior of "back". Well, good question... Perhaps in that case it would help if I add a contentLocation with just the volume and the link to the image instance? I'll try that and will update the issue

**Comment by eroux** [comment]
done, it looks better now, thanks! I'll rework a few minor things in the data but we're almost there!
