### ISSUE TITLE
new line issue in etext display

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#792]
I think the etext viewer adds a new line at the end of chunks where it shouldn't. Example on page 37 of https://library.bdrc.io/show/bdr:UTIE0OPIB6A9B78C_I4PD488?backToEtext=bdr:IE0OPIB6A9B78C#open-viewer 

![Capture d’écran de 2023-01-24 08-29-27](https://user-images.githubusercontent.com/60868/214235999-0f394a43-2c4a-4c5f-b0b4-20422ee12c7b.png)

there are two line breaks that don't occur with the chunks themselves (no `\n`). The chunks are:

UTIE0OPIB6A9B78C_I4PD488_00017

"[...] ༁ྃ༔ རང་སྐད་དུ་ལྷང་ལྷང་༔ དུས་གསུམ་གྱི་རྟོག་ཚོགས་ཐམས་ཅད་རྒྱལ་བ་རྣམས་ཀྱི་མཁྱེན་བརྩེའི་ཡེ་ཤེས་སུ་ཟང་ཐལ་ཐལ་དུ་བསམས་ཤིང་གཞུང་ལྟར་བསྒོམ་བཟླས་ལ་འབད་\nཔར་བྱའོ༔ " (no line break at the end but a line break in the UI)

UTIE0OPIB6A9B78C_I4PD488_00018

"ས་མ་ཡཱ༔ རྒྱ་རྒྱ་རྒྱ༔ གསུམ་པ་རྗེས་ཀྱི་རིམ་པ་ནི༔ དེ་ལྟར་བརྩོན་འགྲུས་བསྐྱེད་དེ་ཉམས་སུ་བླངས་ནས་ཁྲི་བརྒྱད་བཟླས་པས་མདོ་ལས་གསུངས་བའི་ཡོན་ཏན་ཐམས་ཅད་\nའཐོབ་པར་གདོན་མི་ཟ་བས་ཡིད་གཉིས་ཀྱི་འཛིན་པ་སྤངས་ཏེ་ཉམས་སུ་བླང་བར་བྱའོ༔ " (no line break at the beginning or end)

UTIE0OPIB6A9B78C_I4PD488_00019

the rest of the page

This is a somewhat high priority

**Comment by berger-n** [comment]
fixed: https://library-dev.bdrc.io/show/bdr:UTIE0OPIB6A9B78C_I4PD488?startChar=24707&backToEtext=bdr:IE0OPIB6A9B78C#open-viewer

![image](https://user-images.githubusercontent.com/33383857/214268783-36cfc1ec-c52d-40c6-8b2b-730505f64c68.png)

---

found a bug though, when checking how it behaved when some keyword is highlighted: https://library-dev.bdrc.io/search?q=%22%E0%BD%81%E0%BE%B2%E0%BD%B4%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%93%E0%BC%8B%E0%BD%96%E0%BD%8F%E0%BD%82%E0%BD%A6%E0%BC%8B%22~1&lg=bo&t=Etext&pg=1&f=instance,inc,bdr:IE0OPIB6A9B78C

if you click on second result it opens page 37 but first line is missing:

![image](https://user-images.githubusercontent.com/33383857/214272105-c2647eef-05e6-4adc-93fc-0792e031e0fd.png)

because the start index returned by query is that of the chunk, not of the page
I thought we could just link to this `startChar` minus, say, 1000, but it won't work in the case the match is at the very end of the page as it would only add previous chunk, not the one(s) before

(having a look at http://purl.bdrc.io/lib/Chunks?R_RES=bdr%3AUTIE0OPIB6A9B78C_I4PD488&I_START=24967&I_END=34967
first chunk it returns starts at index 24857 which is in the middle of the page)

**Comment by eroux** [comment]
thanks, that looks good!

hmmm, you're right about the search, I never thought of that... perhaps using `start-3000` would be enough?

**Comment by berger-n** [comment]
more than 1000 seems too much in that case:
- with -1000:
  ![image](https://user-images.githubusercontent.com/33383857/214276567-b14a6a0e-a617-4e4e-97d5-e9e6e2fc6a02.png)
---

- with -2000:
  ![image](https://user-images.githubusercontent.com/33383857/214276379-df570de2-6fb7-4acb-a02f-2b6a696092ef.png)
---

- with -3000 (pages 31,33 are shorter, ah and there's no page 32? seems [empty](https://iiif.bdrc.io/bdr:I4PD488::I4PD4880032.tif/full/3500,/0/default.png) indeed):
  ![image](https://user-images.githubusercontent.com/33383857/214276885-8255b449-7b6c-4e17-a4f6-61abf605851d.png)
