### ISSUE TITLE
Searching on etexts

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#803]
Does searching on etexts work the same way as on works+versions?

I just did a search on གཟུངས་སྒྲུབ་ཀྱི་བུམ་ཆུས་ in etexts. In this phrase the last letter (ས་) is the agentive grammatical particle but to me it seems that the search understood ཆུས་ to be a word. Caveat, ཆུས་ is a word but it should also be parsed as ཆུ+ས་ Is this an issue unique to this one word or is it an issue with etext search?

**Comment by JannTibetan** [comment]
Additional details, a search on གཟུངས་སྒྲུབ་ཀྱི་བུམ་ཆུ་ (no ས་) returns results with ཆུ་ ཆུའི and ཆུའམ་ This makes me thing we joist didn't normalize for ཆུས་  What do you think?

BTW གཟུངས་སྒྲུབ་ཀྱི་བུམ་ཆུ means, the vase water used in the dharani accomplishment ritual

**Comment by eroux** [comment]
> Does searching on etexts work the same way as on works+versions?

yes

> I just did a search on གཟུངས་སྒྲུབ་ཀྱི་བུམ་ཆུས་ in etexts. In this phrase the last letter (ས་) is the agentive grammatical particle but to me it seems that the search understood ཆུས་ to be a word.

Correct yes, the search engine currently works at syllable level, and it doesn't normalize `ཆུས` -> `ཆུ` (or any other case with `ས` or `ར`). This is an important limitation of the current search engine. In order to make it better we need a bit of NLP to do some segmentation and syntax analysis (so that the search engine understands that `ཆུས = ཆུ + ས`).

I don't have a very good solution for this... If we normalize everything by removing the `ས` and `ར` suffixes everywhere there's a risk that the search will return irrelevant search results and there's already enough complaints about the search results not being exact enough... so I'm not sure what to do! I still think developing NLP tools and data is the best way forward for this but it takes time

**Comment by eroux** [comment]
Now, something I've had in mind for some time is to make a good list of syllables in which we can be certain that the suffix `ས` / `ར` is morphological, but your example makes me doubt we can make a good list automatically (because we'll find `ཆུས` in dictionaries). If @ngawangtrinley was to come up with a solid list, I can implement it :) The list could be negative or positive: listing syllables where the suffix is always morphological (?), or listing syllables where the suffix may or may not be morphological

**Comment by eroux** [comment]
closing as postponed, we need more resources to have a good system for that

**Comment by JannTibetan** [comment]
Searching on etexts Part Two:
Search for a term, open an etext listed in the search results, and then have **a second search function to make additional and varied searches within that one etext**

**Comment by eroux** [comment]
I'll move that to a separate issue
