### ISSUE TITLE
issue with multiple instances of mirador

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#83]
see https://bdrc-reader.github.io/mugey-gonpa/test

**Comment by berger-n** [comment]
using multiple iframes works flawlessly (copy/pasting from https://github.com/buda-base/public-digital-library/blob/master/BDRC_Embedded_Reader.md#using-an-iframe)

the issue here comes from mixing iframe embedding and [source files embedding](https://github.com/buda-base/public-digital-library/blob/master/BDRC_Embedded_Reader.md#using-source-files)

need to know more about the intended use here I think
@ngawangtrinley do you need more than simple iframe embedding ?

**Comment by berger-n** [comment]
also CSS style should be adjusted:
(multiple iframe with "position:fixed;width:100%;height:100%;" will result in only one instance visible)

**Comment by eroux** [comment]
Thanks! @ngawangtrinley can you check or point to the file that generates the html?
