### ISSUE TITLE
title not displayed in outline but displayed in full record

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#852]
In https://library.bdrc.io/show/bdr:MW20242_O20242_5RMHY2 the title reads `"མདད་བཏང་"ཞེས་པའི་ཐ་སྙད་ཀྱི་གོ་དོན་ལ་རགས་ཙམ་དཔྱད་པ།` but when opening it in the outline (https://library.bdrc.io/show/bdr:MW20242?part=bdr:MW20242_O20242_5RMHY2 , not coming from the previous page), the title is displayed as `[no title]` and in the details as `[object Object]`. It looks like some issue in the jsewts transliteration process, @berger-n can you investigate? Thanks!

**Comment by berger-n** [comment]
fixed: https://library.bdrc.io/show/bdr:MW20242?part=bdr:MW20242_O20242_5RMHY2

![image](https://github.com/buda-base/public-digital-library/assets/33383857/b0dc553e-b8c5-4d3b-b268-7cd1265f2754)
---

oddly enough there's no `@language` tag in the `prefLabel` for this node
(maybe because it starts with a `"`? had to fix language detection a bit because of it):

![image](https://github.com/buda-base/public-digital-library/assets/33383857/40381e87-0047-44e1-8157-368d44dc60b6)
