### ISSUE TITLE
latest searches for users

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#895]
the idea is that when users click on the search bar, but don't type anything, some recent user searches would be listed. I think this is a pretty major feature, but that raises a few questions on the implementation:
- what should the general UI be like? (a quick Figma would be good)
- should we tie the search history to a user or just a browser session?
- (this can be in different stages) should we store the latest searches in the backend or are we ok with the search history being linked to a browser session?
- do we want an button to "clear search history"?

**Comment by roopeux** [comment]
@eroux I did not understand the first question.  The general UI should be as it is, a search bar.

Search history should be as long as possible.

I would not complicate things and start sharing search histories between devices of the same registered user.  It would be a nice-to-have but probably bad cost-benefit.

@berger-n I propose using **localstorage and not a cookie**, because a cookie can get too small.

The way to clear individual search items would be to add an X at the end of each autosuggestion like in the actual search bar, but I don't think it will be worth it.  I struggle finding a use case.

**Comment by roopeux** [comment]
@berger-n The search history should be in chronological order, latest queries first.  When user types, show the matching lines.  (Match from the beginning of string only)

**Comment by eroux** [comment]
in terms of UI, the question is: will there be an indication that the search suggestions come from the user search history? like maybe an icon of a clock?

As long as possible seems like a lot UI-wise, it will take the whole screen in some cases, maybe we can limit to 10?

ok for localstorage yes! let's not have a clear history button for now and see if users ask

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/osearch/search

![simplescreenrecorder-2024-08-19_18 30 26 mkv](https://github.com/user-attachments/assets/b9ae6f64-a059-421e-8aab-8f70014592fb)

some items to discuss/fine tune (see how it works on [Google search](https://www.google.fr/)):
- display maximum of 15 items from history 
- display maximum 5 items from history + 10 from autocomplete

**Comment by eroux** [comment]
wow this is really cool, thanks a lot!

**Comment by roopeux** [comment]
Sorry I have missed this.  The feature works great, but let's limit suggestions in any situation to 10, according to UX best practices.

Typically user's own queries are not visually different, but the way you have done it is very good.
