### ISSUE TITLE
Link top left logo to the dev home page (for test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#919]
For exampe, on https://library-dev.bdrc.io/show/bdr:P258?s=%2Fosearch%2Fsearch%3Fq%3Dmkhyen%2520brtse%2527i%2520dbang%2520po

**Comment by berger-n** [comment]
not sure what you mean @roopeux? to me it already does: 

![Image](https://github.com/user-attachments/assets/772fdd85-35cc-4004-9440-80e16097c495)

**Comment by roopeux** [comment]
Okay I see now, the "BUDA" correctly points to dev but the "BDRC" points to bdrc.io, which is also intentional.

The UX problem is that users see these two as one top-left logo that should take home.  Everyone uses this a lot.  

If the distinction between BUDA and BDRC is very important, we should completely redesign the top row to visually separate the two logos, and put BDRC maybe on the right side.  If not, let's link the whole top left area to BUDA.

@JannTibetan ?

**Comment by eroux** [comment]
This became a different issue, the original one is fixed
