### ISSUE TITLE
Etext search (from test)

### ISSUE THREAD

**Issue by roopeux** [buda-base/public-digital-library#939]
I probably misunderstood what @JannTibetan meant by etext search.  Our current solution is not intuitive for users.

Current: Match etext only
Users expect: Match metadata and etext in texts that have etext.

Current: The checkbox is in the filters
Users expect: Checkbox just under the search box, on the right.

- For @eroux to approve
- I will change the query
- @berger-n can change the checkbox location and change the label to "Etext search"

**Comment by eroux** [comment]
I like the idea of the checkbox near the main search box

About what the query does, I'm not sure I agree, we should change the functionning of the query, it could be just a matter of wording. Perhaps the box could read "only matches within etexts"?

**Comment by eroux** [comment]
BTW, I'm not sure who the user was but it might come from a habit of the legacy website (from many years ago) where there "etext search" was a searching only on etext metadata, not content

**Comment by roopeux** [comment]
This is not based on one user only.  What is your use case for the need to exclude metadata?

**Comment by eroux** [comment]
well actually I would return the question: what's the use case for including metadata? The use case I'm thinking for this check box (and that we discussed earlier) is the following: you have a person name or text title and you want to find places in the etexts where the text title appears, specifically only in the etext content, excluding the metadata (because you're only interested in the references to the text, not in the text itself). I don't see a use case for searching etext + metadata, it's already there in the default search. If we can't find a way to make users understand the check box and don't want to support the use case I described let's just remove it

**Comment by roopeux** [comment]
Let's continue this discussion after we have all seen some user videos, to be more on the same page.

My initial thought is that your use case belongs to advanced search, which we apparently need to build too.

Our filters seem far too complicated for being used correctly.  Even the Buddhist professor, who has been using BDRC for ages, failed to check the right boxes.  Another experienced BDRC user did not see the filters at all, even they would have solved her need immediately.  She noticed them after the test, though.  Anyways, this is too early to suggest anything for the filters.

**Comment by eroux** [comment]
Sure, we can keep it for advanced search! it's not a particularly urgent filter anyway, we don't have to support it in the UI of the first version, but it's good to have it supported in the backend and routes already

**Comment by roopeux** [comment]
This is included in the new [filters design](https://github.com/orgs/buda-base/projects/23/views/1?filterQuery=from+test&pane=issue&itemId=82034286)
